-- AEMT day-one baseline diagnostic — 50 items.
--
-- GENERATED from src/data/aemtBaseline.ts by scripts/build-baseline-sql.mjs.
-- Do not hand-edit: the rationales, the blueprint mix and the item-writing
-- checks all live with the source, and a change made here alone is a change
-- nothing reviews and nothing verifies.
--
-- Requires migration 2026-09-02-aemt-baseline-diagnostic.sql, which admits
-- 'aemt-baseline' as a program.
--
-- ADDITIVE. Clears and reloads only its own rows. Safe while unused; once a
-- student has sat it, retire items instead (see maintenance/retire-items.sql)
-- so the attempts on record keep pointing at what was actually asked.

delete from public.exam_questions where program = 'aemt-baseline';

insert into public.exam_questions (program, code, domain, stem, options, answer, active) values
('aemt-baseline', 'BD-01', 'clinical-judgment', 'You find a 60-year-old man slumped at a table, breathing noisily and not responding to your voice. There is no sign of injury. Your first action is to:', array['obtain a set of baseline vital signs','open the airway with a head-tilt, chin-lift','apply oxygen by nonrebreather mask','ask bystanders when he was last normal'], 1, true),
('aemt-baseline', 'BD-02', 'clinical-judgment', 'A patient who fell is alert and answering questions. Her daughter says she is normally sharp, but she has repeated the same question three times in four minutes. This is best described as:', array['an expected response to the stress of a fall','a long-standing memory problem of her own','a normal variant in patients of her age','a change from her baseline mental status'], 3, true),
('aemt-baseline', 'BD-03', 'clinical-judgment', 'You are treating a patient for respiratory distress. Which finding best indicates that the distress is improving?', array['the pulse oximeter now reads 96 percent','the patient says the mask feels better','the respiratory rate has fallen to 12','full sentences and less accessory muscle use'], 3, true),
('aemt-baseline', 'BD-04', 'clinical-judgment', 'Two patients are down at a single-car crash. One is screaming and holding his leg; the other is quiet with shallow, rapid breathing. You should assess:', array['the silent patient, whose breathing is abnormal','the screaming patient, whose breathing is noisy','both together, dividing your attention evenly','whichever patient is nearer the ambulance'], 0, true),
('aemt-baseline', 'BD-05', 'clinical-judgment', 'A patient with diabetes is confused and sweaty. A family member says she took her insulin but skipped lunch. Your working hypothesis is:', array['an insulin dose that was set too low','an early infection driving the confusion','blood glucose that has fallen too far','blood glucose that has risen too high'], 2, true),
('aemt-baseline', 'BD-06', 'clinical-judgment', 'You are treating a patient for a suspected allergic reaction when they suddenly become difficult to rouse. Your next step is to:', array['continue the treatment already in progress','record the change and reassess in five minutes','obtain a more detailed allergy history','return to the primary survey and reassess'], 3, true),
('aemt-baseline', 'BD-07', 'clinical-judgment', 'A patient with chest pain has a blood pressure of 88/60 with cool, moist skin. As an EMT, your management centers on:', array['assisting the patient with their nitroglycerin','supporting ABCs, requesting ALS, transporting','completing a detailed history before moving','sitting them fully upright to ease the work'], 1, true),
('aemt-baseline', 'BD-08', 'clinical-judgment', 'Your partner says the patient "looks fine" while the patient describes a sense of impending doom. You should:', array['treat it as a reason to reassess carefully','reassure the patient and continue as planned','attribute the feeling to situational anxiety','defer to your partner as the senior provider'], 0, true),
('aemt-baseline', 'BD-09', 'clinical-judgment', 'An older patient taking a beta blocker has lost a significant volume of blood. Compared with a healthy adult, you should expect their heart rate to:', array['rise far higher than you would expect','fall steadily as the bleeding continues','stay lower than the blood loss suggests','track the blood loss in the usual way'], 2, true),
('aemt-baseline', 'BD-10', 'clinical-judgment', 'Which handoff at the emergency department gives the receiving team what it needs?', array['age, complaint, and the treatment you gave','complaint, findings, trend, treatment, response','complaint, the full past history, and medications','age, complaint, and the receiving preference'], 1, true),
('aemt-baseline', 'BD-11', 'clinical-judgment', 'A patient refuses transport after a low-speed collision. Accepting the refusal requires that they:', array['have someone available to drive them home','have no visible injuries of any kind','have signed the refusal paperwork','can reason through it and state a choice'], 3, true),
('aemt-baseline', 'BD-12', 'clinical-judgment', 'Your patient has a respiratory rate of 30 and a pulse oximetry reading of 99 percent. This should prompt you to:', array['accept that oxygenation is adequate','reduce the oxygen you are delivering','recheck the probe on the other hand','look for a cause of the rapid breathing'], 3, true),
('aemt-baseline', 'BD-13', 'clinical-judgment', 'You are dispatched for "back pain" in a 70-year-old woman who is pale and clammy with a pulse of 118. You should treat this as:', array['a potentially life-threatening presentation','a musculoskeletal complaint needing comfort','an anxiety response to the pain itself','a routine transfer to her own hospital'], 0, true),
('aemt-baseline', 'BD-14', 'clinical-judgment', 'Which finding would most concern you in a two-year-old?', array['crying loudly and reaching for the parent','flushed cheeks and a temperature of 101 F','lying quietly and not tracking your movement','refusing to answer any of your questions'], 2, true),
('aemt-baseline', 'BD-15', 'clinical-judgment', 'Halfway to the hospital your patient deteriorates markedly. You should reassess:', array['the specific system you have been treating','the primary survey from the beginning','the vital signs and nothing further','the history for anything you missed'], 1, true),
('aemt-baseline', 'BD-16', 'clinical-judgment', 'You disagree with your partner about whether a patient needs immediate transport. The most appropriate first step is to:', array['state the specific findings that concern you','defer, since the crew needs to agree','transport quietly and discuss it later','ask the patient which they would prefer'], 0, true),
('aemt-baseline', 'BD-17', 'clinical-judgment', 'A patient has warm, dry skin, a weak radial pulse, and capillary refill of four seconds. Together these findings indicate:', array['perfusion that is adequate for now','a reading affected by a cold environment','impaired peripheral perfusion','a normal variant in a well-conditioned adult'], 2, true),
('aemt-baseline', 'BD-18', 'medical-ob-gyn', 'A patient has sudden one-sided weakness. Checking the blood glucose is important because it:', array['identifies a treatable condition that mimics stroke','confirms that the patient is having a stroke','establishes how long the symptoms have lasted','determines which hospital should receive them'], 0, true),
('aemt-baseline', 'BD-19', 'medical-ob-gyn', 'A three-year-old has been seizing for about one minute when you arrive. Your priority is to:', array['hold the limbs still to prevent an injury','cool the child rapidly with wet towels','protect the head and position the airway','move the child to the ambulance at once'], 2, true),
('aemt-baseline', 'BD-20', 'medical-ob-gyn', 'A patient with a known peanut allergy has hives and is now wheezing after eating. This presentation:', array['is a local reaction confined to the skin','will settle without further treatment','is anaphylaxis and indicates epinephrine','reflects anxiety about the exposure'], 2, true),
('aemt-baseline', 'BD-21', 'medical-ob-gyn', 'An unresponsive patient has slow, shallow breathing and pinpoint pupils. Your first priority is to:', array['assist ventilations with a bag-mask device','administer naloxone by the approved route','apply oxygen by nonrebreather mask','check the blood glucose level'], 0, true),
('aemt-baseline', 'BD-22', 'medical-ob-gyn', 'A woman who is 34 weeks pregnant becomes lightheaded and pale while lying flat on the stretcher. You should:', array['raise the legs above the level of the heart','sit her fully upright on the stretcher','position her on her left side','lower the head below the level of the body'], 2, true),
('aemt-baseline', 'BD-23', 'medical-ob-gyn', 'Which finding in a patient with abdominal pain is most concerning?', array['pain that worsens when the abdomen is pressed','a rigid abdomen with a rapid, weak pulse','nausea with two episodes of vomiting','pain that came on gradually over a day'], 1, true),
('aemt-baseline', 'BD-24', 'medical-ob-gyn', 'A dialysis patient has missed their last two sessions. They are most at risk of:', array['a dangerously low blood sugar','an infection at the vascular access site','a sudden drop in blood pressure','fluid overload and high potassium'], 3, true),
('aemt-baseline', 'BD-25', 'medical-ob-gyn', 'A patient reports the worst headache of their life, at full intensity within seconds. This history is most concerning for:', array['a migraine with visual symptoms','a tension headache from stress','a sinus infection behind the eyes','bleeding inside the skull'], 3, true),
('aemt-baseline', 'BD-26', 'medical-ob-gyn', 'During delivery a loop of umbilical cord appears at the vaginal opening ahead of the baby. You should:', array['check the cord for a pulse and reassess','relieve pressure on the cord and transport','position the mother flat and await delivery','clamp the cord in two places and cut it'], 1, true),
('aemt-baseline', 'BD-27', 'medical-ob-gyn', 'An asthmatic patient who was wheezing loudly now has a quiet chest and is difficult to rouse. This change means:', array['the attack is resolving well','the wheezing was misheard earlier','air movement has become inadequate','the inhaler has taken full effect'], 2, true),
('aemt-baseline', 'BD-28', 'medical-ob-gyn', 'Which patient with a fever should be transported most urgently?', array['an adult with a cough and a temperature of 102 F','a child with a rash that does not blanch','a teenager with a sore throat and fever','an adult with fever and generalized body aches'], 1, true),
('aemt-baseline', 'BD-29', 'medical-ob-gyn', 'A patient found in a hot apartment is confused and disoriented after prolonged heat exposure. You should immediately:', array['begin active cooling and move them','give oral fluids to replace the losses','wrap them to prevent further shivering','wait for a core temperature reading'], 0, true),
('aemt-baseline', 'BD-30', 'medical-ob-gyn', 'A patient took an intentional overdose two hours ago and currently appears well. You should:', array['wait on scene for symptoms to appear','strongly encourage transport and contact medical control','accept a refusal once they appear lucid','call the pharmacy for advice before deciding'], 1, true),
('aemt-baseline', 'BD-31', 'cardiology', 'You witness an adult collapse and find no pulse. Your first action is to:', array['deliver two rescue breaths','check the rhythm on the monitor','open the airway and look','begin chest compressions'], 3, true),
('aemt-baseline', 'BD-32', 'cardiology', 'An adult is in cardiac arrest, compressions are underway, and the AED identifies ventricular fibrillation. Alongside high-quality CPR, the most time-critical intervention is:', array['defibrillation without further delay','placement of an advanced airway','transport to the nearest hospital','administration of high-flow oxygen'], 0, true),
('aemt-baseline', 'BD-33', 'cardiology', 'Chest compressions on an average adult should be delivered to a depth of at least:', array['one inch','two inches','four inches','three inches'], 1, true),
('aemt-baseline', 'BD-34', 'cardiology', 'A 58-year-old with chest pain is alert, has no aspirin allergy, has no bleeding, and has taken none today. Within EMT scope you should:', array['withhold aspirin until ALS is on scene','withhold aspirin because of the pain severity','give chewable aspirin per protocol','give aspirin only if the pain is crushing'], 2, true),
('aemt-baseline', 'BD-35', 'cardiology', 'The AED advises "no shock" in a pulseless patient. You should:', array['resume compressions immediately','check the pads and reanalyze','wait for the next analysis cycle','provide ventilations only'], 0, true),
('aemt-baseline', 'BD-36', 'cardiology', 'Which patient carries the greatest risk of an atypical or painless presentation of a heart attack?', array['a young adult who is physically fit','a middle-aged man who smokes heavily','an 80-year-old woman with long-standing diabetes','an adult with a family history of heart disease'], 2, true),
('aemt-baseline', 'BD-37', 'cardiology', 'A patient in cardiac arrest has a defibrillator implanted under the skin below the collarbone. You should:', array['avoid defibrillating this patient','place the pads clear of the device','deactivate the device before shocking','place a pad directly over the device'], 1, true),
('aemt-baseline', 'BD-38', 'airway', 'Which finding is a contraindication to inserting an oropharyngeal airway?', array['snoring respirations in an unresponsive patient','no response to a painful stimulus','an intact gag reflex','blood and secretions in the mouth'], 2, true),
('aemt-baseline', 'BD-39', 'airway', 'You are opening the airway of an unresponsive infant with no suspected injury. The head should be placed:', array['extended as far back as it will go','in a neutral, slightly extended position','flexed forward toward the chest','turned to one side to drain secretions'], 1, true),
('aemt-baseline', 'BD-40', 'airway', 'You are ventilating a child with a bag-mask. Squeezing the bag too fast and too forcefully risks:', array['gastric distension and reduced venous return','rupturing the alveoli in both lungs','delivering an excessive oxygen concentration','cooling and drying the airway too quickly'], 0, true),
('aemt-baseline', 'BD-41', 'airway', 'A conscious adult is choking but can cough forcefully. You should:', array['deliver abdominal thrusts without delay','stay with them and monitor closely','perform a finger sweep between coughs','lay them down and begin back blows'], 1, true),
('aemt-baseline', 'BD-42', 'airway', 'An adult has a strong pulse but is breathing six times per minute with shallow chest rise and increasing drowsiness. You should:', array['apply oxygen by nasal cannula','apply a nonrebreather mask','assist ventilations with a bag-mask and oxygen','apply continuous positive airway pressure'], 2, true),
('aemt-baseline', 'BD-43', 'trauma', 'Firm direct pressure has failed to control bright red bleeding spurting from a forearm wound. Your next intervention is:', array['elevating the limb above the heart','pressing on a proximal pressure point','a commercial tourniquet proximal to the injury','a cold pack applied over the dressing'], 2, true),
('aemt-baseline', 'BD-44', 'trauma', 'A patient is impaled by a metal rod through the thigh. You should:', array['stabilize it in place and pad around it','remove it and pack the wound firmly','shorten it now to simplify the move','loosen it slightly to reduce the pressure'], 0, true),
('aemt-baseline', 'BD-45', 'trauma', 'Which findings in an injured eight-year-old are most consistent with compensated shock?', array['a falling blood pressure with a slow pulse','warm pink hands with a strong radial pulse','a normal heart rate with cool, dry skin','a normal blood pressure with delayed refill'], 3, true),
('aemt-baseline', 'BD-46', 'trauma', 'A patient struck by a car has an obviously deformed femur and is breathing rapidly and shallowly. During the primary assessment, priority goes to:', array['splinting the deformed femur','supporting ventilation and oxygenation','treating the pain the patient reports','documenting the mechanism of injury'], 1, true),
('aemt-baseline', 'BD-47', 'ems-operations', 'You arrive at a collision and see a downed power line lying across the vehicle. You should:', array['approach the vehicle from the opposite side','stay clear and have the utility respond','move the line aside with a dry wooden tool','tell the occupants to step out and away'], 1, true),
('aemt-baseline', 'BD-48', 'ems-operations', 'In START triage at a multiple-casualty incident, a patient who can walk to a designated area is initially tagged:', array['immediate','delayed','minor','expectant'], 2, true),
('aemt-baseline', 'BD-49', 'ems-operations', 'On arrival at an incident involving an unknown chemical, you should first:', array['position uphill and upwind of the scene','approach to read the placard on the tank','begin decontaminating anyone walking out','enter to remove patients from the area'], 0, true),
('aemt-baseline', 'BD-50', 'ems-operations', 'You are approaching a red light with lights and siren operating. You should:', array['proceed once you hear the siren acknowledged','maintain speed while the way ahead looks clear','sound the air horn and continue through','slow or stop, then clear each lane visually'], 3, true);

-- Every item scored, keyed, and inside the blueprint bands its source asserts.
do $$
declare n int;
begin
  select count(*) into n from public.exam_questions where program = 'aemt-baseline';
  if n <> 50 then
    raise exception 'baseline bank loaded % rows, expected 50', n;
  end if;
  select count(*) into n from public.exam_questions
    where program = 'aemt-baseline' and (answer is null or array_length(options, 1) <> 4);
  if n <> 0 then
    raise exception 'baseline bank has % unkeyed or malformed items', n;
  end if;
end $$;
