-- AEMT day-one baseline diagnostic — 50 items.
--
-- GENERATED from src/data/aemtBaseline.ts by scripts/build-baseline-sql.mjs.
-- Do not hand-edit: the rationales, the blueprint mix and the item-writing
-- checks all live with the source, and a change made here alone is a change
-- nothing reviews and nothing verifies.
--
-- Requires migration 2026-09-02-aemt-baseline-diagnostic.sql, which admits
-- 'aemt-baseline' as a program.
--
-- ADDITIVE. Clears and reloads only its own rows. Safe while unused; once a
-- student has sat it, retire items instead (see maintenance/retire-items.sql)
-- so the attempts on record keep pointing at what was actually asked.

delete from public.exam_questions where program = 'aemt-baseline';

insert into public.exam_questions (program, code, domain, stem, options, answer, active) values
('aemt-baseline', 'BD-01', 'clinical-judgment', 'You arrive to find a 60-year-old man slumped at a table, breathing noisily and not responding to your voice. Your first action is to:', array['obtain a set of baseline vital signs','open the airway with a jaw thrust','apply oxygen by nonrebreathing mask','ask bystanders when he was last normal'], 1, true),
('aemt-baseline', 'BD-02', 'clinical-judgment', 'A patient who fell is alert and answering questions, but repeats the same question to you three times in four minutes. This finding is best described as:', array['an expected response to the stress of injury','evidence of a preexisting dementia','a normal variant in older patients','a change in mental status needing transport'], 3, true),
('aemt-baseline', 'BD-03', 'clinical-judgment', 'You have applied oxygen to a patient in respiratory distress. Which finding best tells you the intervention is working?', array['the pulse oximeter now reads 96%','the patient says the mask feels better','the respiratory rate has fallen to 12','the patient is speaking in longer sentences'], 3, true),
('aemt-baseline', 'BD-04', 'clinical-judgment', 'Two patients are down at a single-car crash. One is screaming and holding his leg; the other is quiet with shallow, rapid breathing. You should assess:', array['the silent patient, whose breathing is abnormal','the screaming patient, whose breathing is noisy','both together, dividing your attention evenly','whichever patient is nearer the ambulance'], 0, true),
('aemt-baseline', 'BD-05', 'clinical-judgment', 'A diabetic patient is confused and sweaty. A family member says she took her insulin but skipped lunch. Your working hypothesis is:', array['an insulin dose that was set too low','blood glucose that has fallen too far','an early infection driving the confusion','blood glucose that has risen too high'], 1, true),
('aemt-baseline', 'BD-06', 'clinical-judgment', 'You are treating a patient for a suspected allergic reaction when they suddenly become difficult to rouse. Your next step is to:', array['continue the treatment already in progress','record the change and reassess in five minutes','obtain a more detailed allergy history','return to the primary survey and reassess'], 3, true),
('aemt-baseline', 'BD-07', 'clinical-judgment', 'A patient with chest pain has a blood pressure of 88/60 and cool, moist skin. Which finding would most change your management?', array['a reported pain score of nine out of ten','a history of high blood pressure','the pain having started while at rest','jugular veins that are visibly distended'], 3, true),
('aemt-baseline', 'BD-08', 'clinical-judgment', 'Your partner tells you the patient "looks fine" while the patient tells you they feel a sense of impending doom. You should:', array['treat the feeling as a significant finding','reassure the patient and continue as planned','attribute the feeling to situational anxiety','defer to your partner as the senior provider'], 0, true),
('aemt-baseline', 'BD-09', 'clinical-judgment', 'An elderly patient on a beta blocker has lost a significant volume of blood. Compared with a healthy adult, you should expect their heart rate to:', array['rise far higher than you would expect','stay lower than the blood loss suggests','fall steadily as the bleeding continues','track the blood loss in the usual way'], 1, true),
('aemt-baseline', 'BD-10', 'clinical-judgment', 'You are handing a patient over at the emergency department. The most important element of your report is:', array['a full recitation of the medical history','the exact times each vital sign was taken','why you believe the patient is sick','the route and traffic conditions en route'], 2, true),
('aemt-baseline', 'BD-11', 'clinical-judgment', 'A patient refuses transport after a low-speed collision. Before accepting the refusal you must first establish that they:', array['have someone available to drive them','have no visible injuries at all','have signed the refusal paperwork','can understand the risks of refusing'], 3, true),
('aemt-baseline', 'BD-12', 'clinical-judgment', 'Your patient has a respiratory rate of 30 and a pulse oximetry reading of 99%. This combination should prompt you to:', array['accept that oxygenation is adequate','reduce the oxygen you are delivering','recheck the probe on the other hand','look for a cause of the rapid breathing'], 3, true),
('aemt-baseline', 'BD-13', 'clinical-judgment', 'You are dispatched for "back pain" in a 70-year-old woman who is pale and clammy with a pulse of 118. You should treat this as:', array['a potentially life-threatening presentation','a musculoskeletal complaint needing comfort','an anxiety response to the pain itself','a routine transfer to her own hospital'], 0, true),
('aemt-baseline', 'BD-14', 'clinical-judgment', 'Which set of findings would most concern you in a two-year-old?', array['crying loudly and reaching for the parent','flushed cheeks and a temperature of 38.5°C','lying quietly and not tracking your movement','refusing to answer any of your questions'], 2, true),
('aemt-baseline', 'BD-15', 'clinical-judgment', 'Halfway to hospital your patient’s condition changes markedly. You should reassess:', array['the specific system you have been treating','the primary survey from the beginning','the vital signs and nothing further','the history for anything you missed'], 1, true),
('aemt-baseline', 'BD-16', 'clinical-judgment', 'You disagree with your partner about whether a patient needs immediate transport. The most appropriate first step is to:', array['state the findings that concern you','defer, since the crew must agree','transport quietly and discuss it later','ask the patient which they would prefer'], 0, true),
('aemt-baseline', 'BD-17', 'clinical-judgment', 'A patient’s skin is warm and dry, but their radial pulse is weak and their capillary refill is four seconds. These findings together suggest:', array['perfusion that is adequate for now','a reading affected by a cold environment','a normal variant in a well-conditioned adult','perfusion that is failing despite the skin'], 3, true),
('aemt-baseline', 'BD-18', 'medical-ob-gyn', 'The most reliable way to distinguish a stroke from hypoglycaemia in a patient with one-sided weakness is to:', array['check the blood glucose level','ask when the symptoms began','test the grip strength in both hands','look for a facial droop on one side'], 0, true),
('aemt-baseline', 'BD-19', 'medical-ob-gyn', 'A patient is having a generalised seizure when you arrive. Your priority is to:', array['restrain the limbs to prevent injury','place a bite block between the teeth','protect the head and clear the space','move the patient to the stretcher'], 2, true),
('aemt-baseline', 'BD-20', 'medical-ob-gyn', 'A patient with a known peanut allergy has hives and is now wheezing after eating. This progression indicates:', array['a local reaction confined to the skin','a mild reaction that will settle on its own','an anxiety response to the exposure','a systemic reaction involving the airway'], 3, true),
('aemt-baseline', 'BD-21', 'medical-ob-gyn', 'An unresponsive patient has slow, shallow breathing and pinpoint pupils. The most likely cause is:', array['a narcotic overdose','a stimulant overdose','a diabetic emergency','a head injury'], 0, true),
('aemt-baseline', 'BD-22', 'medical-ob-gyn', 'A woman who is 34 weeks pregnant becomes lightheaded and pale while lying flat on the stretcher. You should:', array['raise the legs above the heart','sit her fully upright on the stretcher','tilt her onto her left side','lower the head below the body'], 2, true),
('aemt-baseline', 'BD-23', 'medical-ob-gyn', 'Which finding in a patient complaining of abdominal pain is most concerning?', array['pain that worsens when the abdomen is pressed','a rigid abdomen with a rapid weak pulse','nausea with two episodes of vomiting','pain that came on gradually over a day'], 1, true),
('aemt-baseline', 'BD-24', 'medical-ob-gyn', 'A dialysis patient has missed their last two sessions. They are most at risk of:', array['a dangerously low blood sugar','a serious infection at the access site','a sudden drop in blood pressure','fluid overload and high potassium'], 3, true),
('aemt-baseline', 'BD-25', 'medical-ob-gyn', 'A patient reports the worst headache of their life, beginning suddenly a few minutes ago. This history most suggests:', array['a migraine with visual symptoms','a tension headache from stress','a sinus infection behind the eyes','bleeding inside the skull'], 3, true),
('aemt-baseline', 'BD-26', 'medical-ob-gyn', 'During delivery the umbilical cord appears at the vaginal opening before the baby. You should:', array['push the cord gently back inside','relieve pressure on the cord and transport','clamp and cut the cord immediately','hold the delivery until hospital arrival'], 1, true),
('aemt-baseline', 'BD-27', 'medical-ob-gyn', 'An asthmatic patient who was wheezing loudly now has a quiet chest and is difficult to rouse. This change means:', array['the attack is resolving well','the wheezing was misheard earlier','air movement has become inadequate','a sedative has taken effect'], 2, true),
('aemt-baseline', 'BD-28', 'medical-ob-gyn', 'Which patient with a fever should be transported most urgently?', array['an adult with a cough and a temperature of 39°C','a child with a rash that does not blanch','a teenager with a sore throat and fever','an adult with fever and body aches'], 1, true),
('aemt-baseline', 'BD-29', 'medical-ob-gyn', 'A patient found in a hot apartment has hot, dry skin and is confused. You should immediately:', array['begin active cooling and move them','give oral fluids to replace losses','wrap them to prevent further shivering','wait for a temperature reading first'], 0, true),
('aemt-baseline', 'BD-30', 'medical-ob-gyn', 'A patient took an intentional overdose two hours ago and now appears well. You should:', array['accept a refusal if they seem lucid','transport, since effects may be delayed','wait on scene for symptoms to appear','contact the pharmacy for advice first'], 1, true),
('aemt-baseline', 'BD-31', 'cardiology', 'You witness an adult collapse and find no pulse. Your first action is to:', array['deliver two rescue breaths','check the rhythm on the monitor','open the airway and look','begin chest compressions'], 3, true),
('aemt-baseline', 'BD-32', 'cardiology', 'The single factor that most improves survival in witnessed cardiac arrest is:', array['early defibrillation with minimal interruption','early placement of an advanced airway','rapid transport to the nearest hospital','early administration of oxygen'], 0, true),
('aemt-baseline', 'BD-33', 'cardiology', 'Chest compressions on an adult should be delivered to a depth of at least:', array['one inch','two inches','four inches','three inches'], 1, true),
('aemt-baseline', 'BD-34', 'cardiology', 'A patient describes pressure in the chest that spreads to the jaw. They are most likely experiencing:', array['a muscular strain in the chest wall','inflammation of the airway lining','reduced blood flow to the heart','a spasm of the oesophagus'], 2, true),
('aemt-baseline', 'BD-35', 'cardiology', 'The AED advises "no shock" in a pulseless patient. You should:', array['resume compressions immediately','check the pads and reanalyse','wait for the next analysis cycle','begin ventilations only'], 0, true),
('aemt-baseline', 'BD-36', 'cardiology', 'Which chest pain patient is most likely to present without pain at all?', array['a young adult who is physically fit','a middle-aged man who smokes','an older woman with diabetes','an adult with a family history of heart disease'], 2, true),
('aemt-baseline', 'BD-37', 'cardiology', 'A patient in cardiac arrest has a defibrillator implanted under the skin. You should:', array['avoid defibrillating this patient','place the pads clear of the device','deactivate the device before shocking','place a pad directly over the device'], 1, true),
('aemt-baseline', 'BD-38', 'airway', 'An oropharyngeal airway should be withheld in a patient who:', array['has noisy, snoring respirations','is unresponsive to painful stimulus','has a gag reflex still present','has secretions pooling in the mouth'], 2, true),
('aemt-baseline', 'BD-39', 'airway', 'The most common cause of airway obstruction in an unresponsive patient is:', array['swelling of the airway tissues','the tongue falling against the pharynx','a foreign body lodged in the throat','secretions collecting in the airway'], 1, true),
('aemt-baseline', 'BD-40', 'airway', 'You are ventilating an adult with a bag-mask. Squeezing the bag too fast and too hard mainly risks:', array['forcing air into the stomach','rupturing the alveoli in the lungs','delivering too much oxygen','cooling the airway too quickly'], 0, true),
('aemt-baseline', 'BD-41', 'airway', 'A conscious adult is choking but can cough forcefully. You should:', array['deliver abdominal thrusts at once','encourage them to keep coughing','perform a finger sweep of the mouth','lay them down and start back blows'], 1, true),
('aemt-baseline', 'BD-42', 'airway', 'A nasal cannula running at six litres per minute delivers approximately:', array['ninety percent oxygen','seventy percent oxygen','forty-four percent oxygen','twenty-one percent oxygen'], 2, true),
('aemt-baseline', 'BD-43', 'trauma', 'Bright red blood is spurting from a wound on the forearm. Your first action is to:', array['apply a tourniquet above the wound','elevate the limb above the heart','apply direct pressure to the wound','pack the wound with gauze'], 2, true),
('aemt-baseline', 'BD-44', 'trauma', 'A patient is impaled by a metal rod through the thigh. You should:', array['stabilise the object where it lies','remove it and control the bleeding','shorten it for ease of transport','rotate it to relieve the pressure'], 0, true),
('aemt-baseline', 'BD-45', 'trauma', 'Which finding is the earliest reliable sign of shock in a healthy young adult?', array['a falling systolic blood pressure','a rising heart rate with cool skin','a loss of consciousness','an absent radial pulse'], 1, true),
('aemt-baseline', 'BD-46', 'trauma', 'A patient struck by a car has an obviously deformed femur and is breathing rapidly and shallowly. You should address:', array['the breathing before the femur','the femur before the breathing','both at once with a second crew','whichever the patient complains of'], 0, true),
('aemt-baseline', 'BD-47', 'ems-operations', 'You arrive at a collision and see a downed power line across the vehicle. You should:', array['approach and check on the occupants','move the line aside with a dry tool','stay clear and request the utility','tell the occupants to climb out'], 2, true),
('aemt-baseline', 'BD-48', 'ems-operations', 'In START triage at a multiple-casualty incident, a patient who can walk to a designated area is initially tagged:', array['immediate','delayed','minor','expectant'], 2, true),
('aemt-baseline', 'BD-49', 'ems-operations', 'On arrival at an incident involving an unknown chemical, you should first:', array['position uphill and upwind of the scene','approach to read the placard on the tank','begin decontaminating anyone walking out','enter to remove patients from the area'], 0, true),
('aemt-baseline', 'BD-50', 'ems-operations', 'Most ambulance collisions at intersections occur because the driver:', array['was travelling above the speed limit','assumed other drivers had yielded','had failed to use the siren at all','was unfamiliar with the local area'], 1, true);

-- Every item scored, keyed, and inside the blueprint bands its source asserts.
do $$
declare n int;
begin
  select count(*) into n from public.exam_questions where program = 'aemt-baseline';
  if n <> 50 then
    raise exception 'baseline bank loaded % rows, expected 50', n;
  end if;
  select count(*) into n from public.exam_questions
    where program = 'aemt-baseline' and (answer is null or array_length(options, 1) <> 4);
  if n <> 0 then
    raise exception 'baseline bank has % unkeyed or malformed items', n;
  end if;
end $$;
