-- AEMT exam question bank seed (120 items). Generated — do not hand-edit.
-- Re-runnable: clears the bank and reloads it.
truncate table public.exam_questions;
insert into public.exam_questions (domain, stem, options, answer) values
('Airway', 'The primary function of the upper airway is to:', array['carry oxygen down to the alveoli','warm, filter, and humidify air','remove carbon dioxide from blood','drive the primary cough reflex'], 1),
('Airway', 'Normal adult resting respiratory rate is:', array['6 to 10','12 to 20','20 to 30','30 to 40'], 1),
('Airway', 'For an adult in respiratory arrest with a pulse, deliver one breath every:', array['3 seconds','5 to 6 seconds','10 seconds','15 seconds'], 1),
('Airway', 'The best sign of adequate artificial ventilation is:', array['gastric distension with each breath','visible chest rise with each breath','rising resistance with each breath','a faster pulse with each breath'], 1),
('Airway', 'A conscious adult with a complete airway obstruction will typically:', array['speak only in short phrases','cough weakly but continuously','be unable to speak or move air','have loud stridor with each breath'], 2),
('Airway', 'A non-rebreather mask at 12–15 L/min delivers an approximate FiO₂ of:', array['about 24 to 28%','about 35 to 40%','about 44 to 60%','about 80 to 95%'], 3),
('Airway', 'Compared to an adult, the pediatric airway has:', array['a smaller tongue and wider airway','a larger tongue and narrower airway','a stiffer, less mobile epiglottis','a longer, more rigid trachea'], 1),
('Airway', 'An oropharyngeal airway (OPA) is contraindicated in a patient who:', array['is apneic and pulseless','has an intact gag reflex','is deeply unresponsive','has lost the gag reflex'], 1),
('Airway', 'A nasopharyngeal airway (NPA) is correctly sized by measuring from the:', array['mouth corner to the earlobe','nostril to the earlobe','nose to the sternal notch','lips to the tip of the chin'], 1),
('Airway', 'Hypoxia is best defined as:', array['excess carbon dioxide in the blood','inadequate oxygen at the tissue level','an elevated respiratory rate','a low circulating blood volume'], 1),
('Airway', 'A patient breathing shallowly at 6/min is best managed with:', array['a nasal cannula at 2 L/min','a non-rebreather at 15 L/min','assisted bag-valve-mask ventilations','coaching to slow the breathing'], 2),
('Airway', 'Pulse oximetry may read falsely high in:', array['severe anemia','carbon monoxide exposure','supplemental oxygen use','a high fever'], 1),
('Airway', 'Agonal respirations are:', array['a form of adequate breathing','slow, gasping, ineffective breaths','rapid, deep, regular breaths','normal breathing during sleep'], 1),
('Airway', 'Capnography (end-tidal CO₂) is used to assess:', array['circulating blood glucose','ventilation and CO₂ elimination','systolic blood pressure','core body temperature'], 1),
('Assessment', 'The first step of every patient encounter is:', array['obtaining the SAMPLE history','sizing up the scene for safety','checking a blood glucose','applying high-flow oxygen'], 1),
('Assessment', 'AVPU assesses:', array['pupil size and reaction','level of consciousness','skin color and perfusion','the severity of pain'], 1),
('Assessment', 'Normal adult resting heart rate is:', array['40 to 60','60 to 100','100 to 120','120 to 140'], 1),
('Assessment', 'Capillary refill is most reliable as a perfusion sign in:', array['older adults','young children','hypothermic patients','patients with vascular disease'], 1),
('Assessment', 'Which is part of the SAMPLE history?', array['skin color and temperature','last oral intake','the current blood pressure','the Glasgow Coma Score'], 1),
('Assessment', 'A normal adult blood pressure is approximately:', array['about 90/60','about 120/80','about 160/100','about 200/120'], 1),
('Assessment', 'The general impression is formed:', array['after a full set of vitals','within seconds of seeing the patient','after the SAMPLE history','on arrival at the hospital'], 1),
('Assessment', 'OPQRST is used primarily to evaluate:', array['the mechanism of injury','the pain or chief complaint','the current medication list','the condition of the skin'], 1),
('Assessment', 'Unequal pupils in a patient with altered mental status may indicate:', array['a normal, expected finding','a possible stroke or head injury','a sign of low blood sugar','the result of ordinary fatigue'], 1),
('Assessment', 'Skin that is cool, pale, and clammy suggests:', array['an infectious fever','poor perfusion or shock','environmental heat stroke','normal, healthy perfusion'], 1),
('Assessment', 'Orthostatic (postural) vital-sign changes suggest:', array['chronic hypertension','low blood volume','an acute stroke','situational anxiety'], 1),
('Assessment', 'An unstable patient should be reassessed at least every:', array['5 minutes','15 minutes','30 minutes','once during transport'], 0),
('Anatomy', '"Distal" means:', array['nearer to the midline','farther from the trunk','closer to the head','toward the front surface'], 1),
('Anatomy', 'The chamber that pumps oxygenated blood to the body is the:', array['right atrium','right ventricle','left atrium','left ventricle'], 3),
('Anatomy', 'Gas exchange in the lungs occurs in the:', array['bronchi','trachea','alveoli','pleura'], 2),
('Anatomy', 'The prefix "brady-" means:', array['fast','slow','difficult','absent'], 1),
('Anatomy', 'Which vessel carries blood away from the heart?', array['a vein','a venule','an artery','a capillary'], 2),
('Anatomy', 'When the diaphragm contracts, it:', array['moves up and forces exhalation','moves down and draws air in','stays fixed and does not move','seals off the upper airway'], 1),
('Anatomy', 'The largest artery in the body is the:', array['carotid','aorta','femoral','pulmonary'], 1),
('Anatomy', 'Red blood cells are produced primarily in the:', array['nervous system','bone marrow','outer skin layers','endocrine glands'], 1),
('Anatomy', '"Anterior" refers to the ____ of the body.', array['back','front','top','side'], 1),
('Anatomy', 'The functional unit of the kidney is the:', array['alveolus','nephron','neuron','hepatocyte'], 1),
('Anatomy', 'The upper chambers of the heart are the:', array['ventricles','atria','valves','septa'], 1),
('Anatomy', 'The suffix "-itis" means:', array['surgical removal','inflammation','abnormal enlargement','chronic pain'], 1),
('Anatomy', 'The medulla oblongata controls:', array['vision and eye movement','breathing and heart rate','fine hand coordination','the digestion of fats'], 1),
('Anatomy', 'Blood returning to the heart from the body enters the:', array['left atrium','right atrium','left ventricle','aorta'], 1),
('Cardiology', 'The adult CPR compression rate is:', array['60 to 80 per minute','80 to 100 per minute','100 to 120 per minute','120 to 140 per minute'], 2),
('Cardiology', 'Adult compression depth is at least:', array['1 inch','1.5 inches','2 inches','3 inches'], 2),
('Cardiology', 'The one-rescuer adult CPR compression-to-ventilation ratio is:', array['15 to 2','30 to 2','5 to 1','10 to 2'], 1),
('Cardiology', 'An AED is indicated for a patient who is:', array['unresponsive but has a pulse','responsive with chest pressure','unresponsive with no pulse','conscious during a seizure'], 2),
('Cardiology', 'Classic acute coronary syndrome presents as:', array['sharp pain that eases with movement','substernal pressure radiating to the arm','pain only when the chest is pressed','pain isolated to one leg'], 1),
('Cardiology', 'Before assisting a patient with prescribed nitroglycerin, a key contraindication to check is:', array['a heart rate above 60','recent erectile-dysfunction medication','a history of high blood pressure','an age over 50 years'], 1),
('Cardiology', 'The natural pacemaker of the heart is the:', array['AV node','SA node','bundle of His','Purkinje fibers'], 1),
('Cardiology', 'High-quality CPR emphasizes:', array['frequent pauses to check a pulse','full recoil with few interruptions','shallow, very rapid compressions','breaths given before compressions'], 1),
('Cardiology', 'In a witnessed adult arrest, the priority after recognizing arrest is:', array['establishing IV access','early compressions and defibrillation','obtaining a 12-lead ECG','notifying the family'], 1),
('Cardiology', 'Left-sided heart failure often presents with:', array['ankle and leg swelling only','pulmonary congestion and dyspnea','neck-vein distension alone','no respiratory findings'], 1),
('Cardiology', 'Nitroglycerin relieves cardiac chest pain primarily by:', array['speeding up the heart rate','dilating vessels and easing workload','thickening the circulating blood','raising the blood pressure'], 1),
('Cardiology', 'Aspirin is given in suspected ACS to:', array['relieve the chest pain','reduce platelet clumping','slow the heart rate','raise the blood pressure'], 1),
('Cardiology', 'In women, the elderly, and diabetics, an MI may present as:', array['crushing chest pain in every case','fatigue and dyspnea without chest pain','leg pain as the only symptom','a complete absence of symptoms'], 1),
('Cardiology', 'If the AED advises "no shock advised" but the patient is pulseless, you should:', array['stop CPR and reassess','resume CPR immediately','wait for medical direction','remove the AED pads'], 1),
('Medical', 'Hypoglycemia typically presents with:', array['warm, dry skin with slow onset','sweating, tremor, and confusion','deep breathing with fruity odor','a slow pulse and high pressure'], 1),
('Medical', 'Treatment for a conscious hypoglycemic patient who can swallow is:', array['intravenous dextrose','oral glucose','intramuscular glucagon','withholding all sugar'], 1),
('Medical', 'Anaphylaxis (hypotension, hives, wheezing) is treated with:', array['an oral antihistamine','intramuscular epinephrine','sublingual nitroglycerin','oral activated charcoal'], 1),
('Medical', '"FAST" screens for:', array['a heart attack','a stroke','a seizure','sepsis'], 1),
('Medical', 'Tripod positioning with audible wheezing most suggests:', array['a bronchospasm such as asthma','a tension pneumothorax','an ordinary fainting spell','an episode of high blood sugar'], 0),
('Medical', 'The best position for a conscious patient in severe respiratory distress (no trauma) is:', array['lying flat on the back','head-down (Trendelenburg)','sitting fully upright','lying face-down (prone)'], 2),
('Medical', 'Kussmaul respirations with fruity breath suggest:', array['low blood sugar','diabetic ketoacidosis','an opioid overdose','an acute stroke'], 1),
('Medical', 'Outcome in an ischemic stroke depends most on:', array['giving oxygen alone','rapid transport to a stroke center','lowering the pressure on scene','giving oral aspirin'], 1),
('Medical', 'A seizure lasting > 5 minutes, or repeated seizures without recovery, is:', array['a routine febrile seizure','status epilepticus','a fainting episode','a transient ischemic attack'], 1),
('Medical', 'The most rapidly correctable cause of altered mental status for EMS is:', array['an acute stroke','low blood sugar','a brain tumor','a severe migraine'], 1),
('Medical', 'Suspected opioid overdose presents with:', array['wide pupils and fast breathing','pinpoint pupils and slow breathing','high pressure with seizures','a sweet, fruity breath odor'], 1),
('Medical', 'Cool, moist skin with heavy sweating after exertion in the heat suggests:', array['hot, dry skin and confusion','heat exhaustion','shivering with low temperature','sweating from low blood sugar'], 1),
('Medical', 'Hot skin with altered mental status and a very high temperature indicates:', array['painful muscle cramps only','cool, sweaty skin with thirst','heat stroke','a low-grade infectious fever'], 2),
('Medical', 'A patient found in a closed garage with a running car, headache, and confusion should be treated for:', array['an ordinary migraine','carbon monoxide poisoning','a panic or anxiety attack','simple dehydration'], 1),
('Medical', 'A severe asthma attack with a "silent chest" indicates:', array['the attack is improving','an ominous sign needing rapid transport','a reason to withhold oxygen','a need to lay the patient flat'], 1),
('Medical', 'A patient with severe abdominal pain, rigidity, and guarding should be:', array['given food and water','kept NPO in a position of comfort','encouraged to walk it off','given oral glucose'], 1),
('Trauma', 'The first action for severe external extremity bleeding is:', array['elevate the extremity','press on a pressure point','apply firm direct pressure','apply a tourniquet at once'], 2),
('Trauma', 'A tourniquet is indicated when:', array['whenever any bleeding is seen','direct pressure fails on a limb','only after 30 minutes of pressure','never in the prehospital setting'], 1),
('Trauma', 'Early (compensated) shock presents as:', array['low pressure with a slow pulse','fast pulse, pale skin, normal pressure','warm, flushed skin, slow pulse','no change until sudden collapse'], 1),
('Trauma', 'A falling blood pressure in a trauma patient indicates:', array['early compensated shock','late decompensated shock','adequate perfusion','a simple fainting response'], 1),
('Trauma', 'The preferred airway maneuver with suspected spinal injury is:', array['head-tilt, chin-lift','modified jaw-thrust','tilting the neck back','no airway maneuver'], 1),
('Trauma', 'Tension pneumothorax signs include:', array['slow pulse and high pressure','worsening dyspnea, absent breath sounds','wheezing in both lungs','relief that builds with each breath'], 1),
('Trauma', 'An open ("sucking") chest wound is initially covered with:', array['dry gauze sealed on four sides','an occlusive dressing vented on three sides','left open to the air','a snug tourniquet above it'], 1),
('Trauma', 'The "Golden Hour/Period" concept emphasizes:', array['scene time can run as needed','minimizing time to surgical care','requiring 60 minutes on scene','delaying transport for assessment'], 1),
('Trauma', 'A suspected pelvic fracture with signs of shock needs:', array['log-rolling onto the pelvis','a pelvic binder and rapid transport','walking to test its stability','no specific intervention'], 1),
('Trauma', 'Distributive shock (septic, neurogenic) results primarily from:', array['loss of circulating blood','widespread vessel dilation','failure of the heart pump','a blockage to blood flow'], 1),
('Trauma', 'Neurogenic shock classically presents with:', array['a fast pulse and cool skin','low pressure, slow pulse, warm skin','elevated blood pressure','a quick, spontaneous recovery'], 1),
('Trauma', 'An abdominal evisceration should be covered with:', array['dry gauze, organs pushed back in','a moist sterile dressing over them','a tourniquet around the abdomen','nothing until arrival'], 1),
('Trauma', 'The most immediately life-threatening bleeding to control is:', array['slow capillary oozing','bright-red arterial spurting','a shallow surface scrape','an older, healing bruise'], 1),
('Trauma', 'A burn that is dry, white/leathery or charred, and painless is:', array['a red, painful superficial burn','a blistered, moist burn','a dry, leathery, painless burn','a mild, peeling sunburn'], 2),
('Trauma', 'By the adult "rule of nines," the entire anterior torso is approximately:', array['about 9%','about 18%','about 27%','about 36%'], 1),
('Trauma', 'Initial management of a dry chemical (powder) burn is to:', array['flush immediately with water','brush it off, then flush with water','neutralize it with a base or acid','cover it without cleaning'], 1),
('Pharmacology', 'The "rights" of medication administration include patient, drug, dose, route, and:', array['color','time','temperature','manufacturer'], 1),
('Pharmacology', 'Which route gives the fastest systemic effect?', array['oral','subcutaneous','intravenous','transdermal'], 2),
('Pharmacology', 'Naloxone reverses:', array['a benzodiazepine overdose','an opioid overdose','a beta-blocker overdose','alcohol intoxication'], 1),
('Pharmacology', 'A "contraindication" means the drug:', array['should be given at a higher dose','should not be given','will work best here','has no effect'], 1),
('Pharmacology', 'Order: 0.3 mg. Vial: 1 mg/mL. Volume to draw:', array['0.15 mL','0.3 mL','0.6 mL','3 mL'], 1),
('Pharmacology', 'Infuse 1,000 mL over 8 hours with a 10 gtt/mL set. The drip rate is about:', array['10 gtt/min','21 gtt/min','42 gtt/min','125 gtt/min'], 1),
('Pharmacology', 'The "generic name" of a drug is:', array['the brand or trade name','the official non-proprietary name','the name of the manufacturer','the standard adult dose'], 1),
('Pharmacology', 'An "indication" for a medication is:', array['a reason to withhold the drug','a condition the drug treats','an unwanted side effect','the expiration date'], 1),
('Pharmacology', '"Sublingual" administration places the drug:', array['on the skin surface','under the tongue','into a muscle','into a vein'], 1),
('Pharmacology', 'In anaphylaxis, epinephrine causes:', array['vessel dilation and airway narrowing','vessel narrowing and airway opening','a slowing of the heart rate','no effect on the airway'], 1),
('Pharmacology', 'Order: give 1 mg. On hand: 1 mg in 10 mL (1:10,000). You administer:', array['1 mL','10 mL','0.1 mL','100 mL'], 1),
('Pharmacology', 'Convert 0.5 g to milligrams:', array['5 mg','50 mg','500 mg','5,000 mg'], 2),
('Pharmacology', 'A patient weighs 176 lb. That is approximately:', array['about 60 kg','about 70 kg','about 80 kg','about 88 kg'], 2),
('Pharmacology', 'Order: 2 mg/kg for an 80 kg patient. Total dose:', array['40 mg','80 mg','160 mg','320 mg'], 2),
('OB/Peds', 'A sign of imminent delivery is:', array['contractions ten minutes apart','crowning of the head','membranes that have ruptured','persistent lower back pain'], 1),
('OB/Peds', 'Immediately after a newborn delivers, the first priorities are to:', array['cut the cord and weigh the baby','dry, warm, position, and stimulate','give a small amount of glucose','begin compressions on the baby'], 1),
('OB/Peds', 'Compared to adults, a child''s earliest sign of respiratory trouble is:', array['a drop in blood pressure','increased work of breathing','an early drop in heart rate','a complaint of chest pain'], 1),
('OB/Peds', 'Bradycardia in an infant is most often caused by:', array['pain','hypoxia','fever','anxiety'], 1),
('OB/Peds', 'After the newborn''s head delivers, you should:', array['pull firmly to speed delivery','support it and check for a cord','push the head back gently','clamp the cord right away'], 1),
('OB/Peds', 'A prolapsed umbilical cord requires:', array['pushing the cord back inside','lifting the presenting part off the cord','clamping and cutting the cord','holding transport until delivery'], 1),
('OB/Peds', 'The APGAR score assesses all of the following EXCEPT:', array['heart rate','blood glucose','respiratory effort','skin color'], 1),
('OB/Peds', 'Newborn resuscitation adds chest compressions if the heart rate is below:', array['100','60','40','80'], 1),
('OB/Peds', 'A key tool unique to pediatric assessment is the:', array['rule of nines','Pediatric Assessment Triangle','OPQRST mnemonic','Cincinnati stroke scale'], 1),
('OB/Peds', 'The leading cause of cardiac arrest in children is:', array['primary heart disease','respiratory failure','trauma alone','poisoning'], 1),
('Operations', 'Obtaining a competent adult''s permission before treatment is:', array['implied consent','expressed consent','involuntary consent','no consent needed'], 1),
('Operations', 'A competent adult refusing care must be informed of the risks and:', array['treated against their wishes','sign a refusal after being informed','be physically restrained','have care stopped without a record'], 1),
('Operations', 'HIPAA primarily protects:', array['scene and crew safety','patient health information','vehicle maintenance records','radio channel assignments'], 1),
('Operations', '"Standard of care" is best defined as:', array['whatever the provider prefers','what a reasonable, similar provider would do','only what hospital policy says','only what the patient requests'], 1),
('Operations', 'Abandonment occurs when a provider:', array['hands off to an equal level with report','stops care without an equal handoff','declines to enter an unsafe scene','completes thorough documentation'], 1),
('Operations', 'When lifting a heavy patient, you should:', array['bend at the waist to reach','lift with the legs, back straight','twist the torso while lifting','hold the weight away from you'], 1),
('Operations', 'The most important reason for accurate documentation is that it:', array['passes the time on shift','is a legal record of care','is only used for billing','impresses supervisors'], 1),
('Operations', 'Which is a HIPAA-permitted disclosure?', array['posting details on social media','sharing with the receiving hospital','telling a friend about it','discussing it in a public space'], 1),
('Operations', 'Medical direction consisting of protocols and standing orders is called:', array['online (direct) medical direction','offline (indirect) medical direction','verbal orders only','none of these'], 1),
('Operations', 'At a multi-casualty incident, the primary purpose of the Incident Command System (ICS) is to:', array['to assign blame afterward','to coordinate resources and personnel','to replace patient triage','to speed up the billing'], 1);
