-- AEMT exam question bank seed (120 items). Generated — do not hand-edit.
-- Re-runnable: clears the bank and reloads it.
truncate table public.exam_questions;
insert into public.exam_questions (domain, stem, options, answer) values
('Airway', 'The primary function of the upper airway is to:', array['exchange O₂ and CO₂','warm, filter, and humidify air','produce surfactant','trigger the cough reflex'], 1),
('Airway', 'Normal adult resting respiratory rate is:', array['6–10','12–20','20–30','30–40'], 1),
('Airway', 'For an adult in respiratory arrest with a pulse, deliver one breath every:', array['3 seconds','5–6 seconds','10 seconds','15 seconds'], 1),
('Airway', 'The best sign of adequate artificial ventilation is:', array['gastric distension','visible chest rise','rising airway resistance','falling SpO₂'], 1),
('Airway', 'A conscious adult with a complete airway obstruction will typically:', array['speak in full sentences','cough forcefully','be unable to speak or cough','have loud stridor with good air movement'], 2),
('Airway', 'A non-rebreather mask at 12–15 L/min delivers an approximate FiO₂ of:', array['24–28%','35–40%','44–60%','80–95%'], 3),
('Airway', 'Compared to an adult, the pediatric airway has:', array['a proportionally smaller tongue','a proportionally larger tongue and narrower airway','a stiffer epiglottis','a wider trachea'], 1),
('Airway', 'An oropharyngeal airway (OPA) is contraindicated in a patient who:', array['is apneic','has an intact gag reflex','is unresponsive','has no gag reflex'], 1),
('Airway', 'A nasopharyngeal airway (NPA) is correctly sized by measuring from the:', array['corner of the mouth to the earlobe','nostril to the earlobe','nose to the sternum','lips to the chin'], 1),
('Airway', 'Hypoxia is best defined as:', array['increased CO₂ in the blood','inadequate oxygen at the tissue/cellular level','rapid breathing','low blood pressure'], 1),
('Airway', 'A patient breathing shallowly at 6/min is best managed with:', array['a nasal cannula at 2 L/min','a non-rebreather at 15 L/min','assisted ventilations with a BVM','coaching to breathe slower'], 2),
('Airway', 'Pulse oximetry may read falsely high in:', array['anemia','carbon monoxide poisoning','hyperoxia','fever'], 1),
('Airway', 'Agonal respirations are:', array['a sign of adequate breathing','slow, gasping, ineffective breaths often seen in early cardiac arrest','rapid deep breaths','normal during sleep'], 1),
('Airway', 'Capnography (end-tidal CO₂) is used to assess:', array['blood glucose','ventilation / CO₂ elimination','blood pressure','temperature'], 1),
('Assessment', 'The first step of every patient encounter is:', array['the SAMPLE history','scene size-up / ensuring safety','a blood glucose','applying oxygen'], 1),
('Assessment', 'AVPU assesses:', array['pupils','level of consciousness','perfusion','pain severity'], 1),
('Assessment', 'Normal adult resting heart rate is:', array['40–60','60–100','100–120','120–140'], 1),
('Assessment', 'Capillary refill is most reliable as a perfusion sign in:', array['older adults','children','hypothermic patients','patients with vascular disease'], 1),
('Assessment', 'Which is part of the SAMPLE history?', array['skin color','last oral intake','blood pressure','GCS'], 1),
('Assessment', 'A normal adult blood pressure is approximately:', array['90/60 or lower','120/80','160/100','200/120'], 1),
('Assessment', 'The general impression is formed:', array['after full vitals','within the first seconds of seeing the patient','only after the SAMPLE history','at the hospital'], 1),
('Assessment', 'OPQRST is used primarily to evaluate:', array['trauma mechanism','a patient''s pain / chief complaint','the medication list','skin condition'], 1),
('Assessment', 'Unequal pupils in a patient with altered mental status may indicate:', array['a normal finding, always','a possible stroke or head injury','hypoglycemia','simple fatigue'], 1),
('Assessment', 'Skin that is cool, pale, and clammy suggests:', array['fever','poor perfusion / shock','heat stroke','normal perfusion'], 1),
('Assessment', 'Orthostatic (postural) vital-sign changes suggest:', array['hypertension','volume depletion / hypovolemia','stroke','anxiety only'], 1),
('Assessment', 'An unstable patient should be reassessed at least every:', array['5 minutes','15 minutes','30 minutes','once en route'], 0),
('Anatomy', '"Distal" means:', array['toward the midline','farther from the trunk / point of attachment','toward the head','toward the front'], 1),
('Anatomy', 'The chamber that pumps oxygenated blood to the body is the:', array['right atrium','right ventricle','left atrium','left ventricle'], 3),
('Anatomy', 'Gas exchange in the lungs occurs in the:', array['bronchi','trachea','alveoli','pleura'], 2),
('Anatomy', 'The prefix "brady-" means:', array['fast','slow','difficult','absent'], 1),
('Anatomy', 'Which vessel carries blood away from the heart?', array['vein','venule','artery','capillary'], 2),
('Anatomy', 'When the diaphragm contracts, it:', array['moves up, causing exhalation','moves down, increasing thoracic volume (inhalation)','does not change volume','closes the glottis'], 1),
('Anatomy', 'The largest artery in the body is the:', array['carotid','aorta','femoral','pulmonary artery'], 1),
('Anatomy', 'Red blood cells are produced primarily in the:', array['nervous system','bone marrow (skeletal system)','skin','endocrine glands'], 1),
('Anatomy', '"Anterior" refers to the ____ of the body.', array['back','front','top','side'], 1),
('Anatomy', 'The functional unit of the kidney is the:', array['alveolus','nephron','neuron','hepatocyte'], 1),
('Anatomy', 'The upper chambers of the heart are the:', array['ventricles','atria','valves','septa'], 1),
('Anatomy', 'The suffix "-itis" means:', array['removal','inflammation','enlargement','pain'], 1),
('Anatomy', 'The medulla oblongata controls:', array['vision','basic life functions such as breathing and heart rate','fine hand movement','fat digestion'], 1),
('Anatomy', 'Blood returning to the heart from the body enters the:', array['left atrium','right atrium','left ventricle','aorta'], 1),
('Cardiology', 'The adult CPR compression rate is:', array['60–80 /min','80–100 /min','100–120 /min','120–140 /min'], 2),
('Cardiology', 'Adult compression depth is at least:', array['1 in','1.5 in','2 in (~5 cm)','3 in'], 2),
('Cardiology', 'The one-rescuer adult CPR compression-to-ventilation ratio is:', array['15:2','30:2','5:1','10:2'], 1),
('Cardiology', 'An AED is indicated for a patient who is:', array['unresponsive with a pulse','responsive with chest pain','unresponsive, apneic, and pulseless','actively seizing'], 2),
('Cardiology', 'Classic acute coronary syndrome presents as:', array['sharp pain relieved by movement','substernal pressure that may radiate to the arm/jaw','pain only on palpation','isolated leg pain'], 1),
('Cardiology', 'Before assisting a patient with prescribed nitroglycerin, a key contraindication to check is:', array['HR > 60','recent erectile-dysfunction drug use (e.g., sildenafil)','a history of hypertension','age > 50'], 1),
('Cardiology', 'The natural pacemaker of the heart is the:', array['AV node','SA node','bundle of His','Purkinje fibers'], 1),
('Cardiology', 'High-quality CPR emphasizes:', array['frequent long pauses','full chest recoil and minimizing interruptions','shallow, fast compressions','ventilating before compressions in adults'], 1),
('Cardiology', 'In a witnessed adult arrest, the priority after recognizing arrest is:', array['IV access','early compressions and early defibrillation','a 12-lead','family notification'], 1),
('Cardiology', 'Left-sided heart failure often presents with:', array['peripheral edema only','pulmonary edema / crackles and dyspnea','JVD without lung findings','no respiratory symptoms'], 1),
('Cardiology', 'Nitroglycerin relieves cardiac chest pain primarily by:', array['increasing heart rate','dilating vessels (reducing cardiac workload)','thickening the blood','raising blood pressure'], 1),
('Cardiology', 'Aspirin is given in suspected ACS to:', array['relieve pain','inhibit platelet aggregation','lower heart rate','raise blood pressure'], 1),
('Cardiology', 'In women, the elderly, and diabetics, an MI may present as:', array['crushing chest pain, always','an atypical picture (fatigue, dyspnea, weakness) without classic chest pain','leg pain only','no symptoms are possible'], 1),
('Cardiology', 'If the AED advises "no shock advised" but the patient is pulseless, you should:', array['stop CPR','immediately resume CPR','wait for medical direction','remove the pads'], 1),
('Medical', 'Hypoglycemia typically presents with:', array['warm, dry skin and slow onset','altered mental status, diaphoresis, tachycardia','Kussmaul respirations and fruity breath','bradycardia and hypertension'], 1),
('Medical', 'Treatment for a conscious hypoglycemic patient who can swallow is:', array['IV dextrose','oral glucose','IM glucagon','withholding sugar'], 1),
('Medical', 'Anaphylaxis (hypotension, hives, wheezing) is treated with:', array['an oral antihistamine only','epinephrine','nitroglycerin','activated charcoal'], 1),
('Medical', '"FAST" screens for:', array['MI','stroke','seizure','sepsis'], 1),
('Medical', 'Tripod positioning with audible wheezing most suggests:', array['bronchoconstriction (asthma/COPD)','tension pneumothorax','a simple faint','hyperglycemia'], 0),
('Medical', 'The best position for a conscious patient in severe respiratory distress (no trauma) is:', array['supine','Trendelenburg','sitting upright / position of comfort','prone'], 2),
('Medical', 'Kussmaul respirations with fruity breath suggest:', array['hypoglycemia','diabetic ketoacidosis','opioid overdose','stroke'], 1),
('Medical', 'Outcome in an ischemic stroke depends most on:', array['oxygen alone','rapid recognition and transport to a stroke center (time)','lowering blood pressure in the field','oral aspirin'], 1),
('Medical', 'A seizure lasting > 5 minutes, or repeated seizures without recovery, is:', array['a normal febrile seizure','status epilepticus (an emergency)','a syncopal episode','a TIA'], 1),
('Medical', 'The most rapidly correctable cause of altered mental status for EMS is:', array['stroke','hypoglycemia','a tumor','migraine'], 1),
('Medical', 'Suspected opioid overdose presents with:', array['dilated pupils and tachypnea','pinpoint pupils, respiratory depression, decreased LOC','hypertension and seizures','fruity breath'], 1),
('Medical', 'Cool, moist skin with heavy sweating after exertion in the heat suggests:', array['heat stroke','heat exhaustion','hypothermia','hypoglycemia'], 1),
('Medical', 'Hot skin with altered mental status and a very high temperature indicates:', array['heat cramps','heat exhaustion','heat stroke (a true emergency)','fever from infection only'], 2),
('Medical', 'A patient found in a closed garage with a running car, headache, and confusion should be treated for:', array['a simple migraine','carbon monoxide poisoning','anxiety','dehydration'], 1),
('Medical', 'A severe asthma attack with a "silent chest" indicates:', array['improvement','an ominous sign requiring aggressive support and rapid transport','that oxygen should be withheld','the need for supine positioning'], 1),
('Medical', 'A patient with severe abdominal pain, rigidity, and guarding should be:', array['given food and water','transported in a position of comfort, nothing by mouth','encouraged to walk it off','given oral glucose'], 1),
('Trauma', 'The first action for severe external extremity bleeding is:', array['elevation','pressure points','direct pressure','an immediate tourniquet regardless of severity'], 2),
('Trauma', 'A tourniquet is indicated when:', array['any bleeding is present','direct pressure fails to control life-threatening extremity hemorrhage','only after 30 minutes of pressure','never in the field'], 1),
('Trauma', 'Early (compensated) shock presents as:', array['hypotension and bradycardia','tachycardia, anxiety, pale/cool skin, with near-normal BP','warm, flushed skin and bradycardia','no mental-status change until death'], 1),
('Trauma', 'A falling blood pressure in a trauma patient indicates:', array['early compensated shock','decompensated (late) shock','adequate perfusion','a vasovagal response'], 1),
('Trauma', 'The preferred airway maneuver with suspected spinal injury is:', array['head-tilt/chin-lift','modified jaw-thrust','neck hyperextension','none'], 1),
('Trauma', 'Tension pneumothorax signs include:', array['bradycardia and hypertension','progressive dyspnea, decreased breath sounds on the affected side, JVD, hypotension','bilateral wheezing','improvement with each breath'], 1),
('Trauma', 'An open ("sucking") chest wound is initially covered with:', array['dry gauze taped on 4 sides','an occlusive dressing (vented or taped on 3 sides)','nothing','a tourniquet'], 1),
('Trauma', 'The "Golden Hour/Period" concept emphasizes:', array['unlimited scene time','minimizing time to definitive (surgical) care for critical trauma','a required 60 minutes on scene','delaying transport for a full assessment'], 1),
('Trauma', 'A suspected pelvic fracture with signs of shock needs:', array['a log-roll onto the pelvis','a pelvic binder and rapid transport','ambulation to test stability','no intervention'], 1),
('Trauma', 'Distributive shock (septic, neurogenic) results primarily from:', array['blood loss','widespread vasodilation','pump failure','obstruction to flow'], 1),
('Trauma', 'Neurogenic shock classically presents with:', array['tachycardia and cool skin','hypotension with a normal or slow heart rate and warm skin','hypertension','rapid recovery'], 1),
('Trauma', 'An abdominal evisceration should be covered with:', array['dry gauze, organs pushed back in','a moist sterile dressing, organs left in place','a tourniquet','nothing'], 1),
('Trauma', 'The most immediately life-threatening bleeding to control is:', array['minor capillary oozing','bright-red spurting arterial hemorrhage','a small laceration','an old bruise'], 1),
('Trauma', 'A burn that is dry, white/leathery or charred, and painless is:', array['superficial','partial-thickness','full-thickness (third-degree)','sunburn'], 2),
('Trauma', 'By the adult "rule of nines," the entire anterior torso is approximately:', array['9%','18%','27%','36%'], 1),
('Trauma', 'Initial management of a dry chemical (powder) burn is to:', array['apply water immediately','brush off the powder first, then flush with copious water','neutralize with an acid/base','cover it without cleaning'], 1),
('Pharmacology', 'The "rights" of medication administration include patient, drug, dose, route, and:', array['color','time','temperature','manufacturer'], 1),
('Pharmacology', 'Which route gives the fastest systemic effect?', array['oral','subcutaneous','intravenous','transdermal'], 2),
('Pharmacology', 'Naloxone reverses:', array['benzodiazepine overdose','opioid overdose','beta-blocker overdose','alcohol intoxication'], 1),
('Pharmacology', 'A "contraindication" means the drug:', array['needs a higher dose','should NOT be given (may cause harm)','works best','has no effect'], 1),
('Pharmacology', 'Order: 0.3 mg. Vial: 1 mg/mL. Volume to draw:', array['0.15 mL','0.3 mL','0.6 mL','3 mL'], 1),
('Pharmacology', 'Infuse 1,000 mL over 8 hours with a 10 gtt/mL set. The drip rate is about:', array['10 gtt/min','21 gtt/min','42 gtt/min','125 gtt/min'], 1),
('Pharmacology', 'The "generic name" of a drug is:', array['the brand/trade name','the non-proprietary (official) name','the manufacturer','the dose'], 1),
('Pharmacology', 'An "indication" for a medication is:', array['a reason NOT to give it','a condition for which the drug is appropriate','a side effect','its expiration'], 1),
('Pharmacology', '"Sublingual" administration places the drug:', array['on the skin','under the tongue','in the muscle','in a vein'], 1),
('Pharmacology', 'In anaphylaxis, epinephrine causes:', array['vasodilation and bronchoconstriction','vasoconstriction and bronchodilation','a lower heart rate','no airway effect'], 1),
('Pharmacology', 'Order: give 1 mg. On hand: 1 mg in 10 mL (1:10,000). You administer:', array['1 mL','10 mL','0.1 mL','100 mL'], 1),
('Pharmacology', 'Convert 0.5 g to milligrams:', array['5 mg','50 mg','500 mg','5,000 mg'], 2),
('Pharmacology', 'A patient weighs 176 lb. That is approximately:', array['60 kg','70 kg','80 kg','88 kg'], 2),
('Pharmacology', 'Order: 2 mg/kg for an 80 kg patient. Total dose:', array['40 mg','80 mg','160 mg','320 mg'], 2),
('OB/Peds', 'A sign of imminent delivery is:', array['contractions 10 minutes apart','crowning','ruptured membranes alone','back pain'], 1),
('OB/Peds', 'Immediately after a newborn delivers, the first priorities are to:', array['cut the cord and weigh the baby','dry, warm, position, and stimulate; assess breathing/HR','give oral glucose','begin compressions on every newborn'], 1),
('OB/Peds', 'Compared to adults, a child''s earliest sign of respiratory trouble is:', array['hypotension','increased work of breathing (retractions, flaring, grunting)','early bradycardia','chest pain'], 1),
('OB/Peds', 'Bradycardia in an infant is most often caused by:', array['pain','hypoxia','fever','anxiety'], 1),
('OB/Peds', 'After the newborn''s head delivers, you should:', array['pull firmly on the head','support the head and check for a nuchal cord','push the head back','clamp the cord immediately'], 1),
('OB/Peds', 'A prolapsed umbilical cord requires:', array['pushing the cord back in','positioning the mother hips-up, holding the presenting part off the cord, and rapid transport','clamping and cutting the cord','delaying transport'], 1),
('OB/Peds', 'The APGAR score assesses all of the following EXCEPT:', array['heart rate','blood glucose','respiratory effort','color'], 1),
('OB/Peds', 'Newborn resuscitation adds chest compressions if the heart rate is below:', array['100','60','40','80'], 1),
('OB/Peds', 'A key tool unique to pediatric assessment is the:', array['rule of nines','Pediatric Assessment Triangle (appearance, work of breathing, circulation)','OPQRST','Cincinnati scale'], 1),
('OB/Peds', 'The leading cause of cardiac arrest in children is:', array['primary cardiac disease','respiratory failure / hypoxia','trauma only','poisoning'], 1),
('Operations', 'Obtaining a competent adult''s permission before treatment is:', array['implied consent','expressed (informed) consent','involuntary consent','not required'], 1),
('Operations', 'A competent adult refusing care must be informed of the risks and:', array['treated anyway','allowed to acknowledge/sign a refusal after understanding the consequences','restrained','have care withheld without documentation'], 1),
('Operations', 'HIPAA primarily protects:', array['scene safety','a patient''s protected health information / privacy','ambulance maintenance records','EMS radio frequencies'], 1),
('Operations', '"Standard of care" is best defined as:', array['whatever the EMT chooses','the care a similarly trained, reasonable provider would give in similar circumstances','hospital policy only','the patient''s preference'], 1),
('Operations', 'Abandonment occurs when a provider:', array['transfers care to an equal/higher level with report','terminates care without ensuring an equal or higher level of care','refuses an unsafe scene','documents thoroughly'], 1),
('Operations', 'When lifting a heavy patient, you should:', array['bend at the waist','keep the back straight, lift with the legs, load close to the body','twist while lifting','hold the load away from you'], 1),
('Operations', 'The most important reason for accurate documentation is that it:', array['fills time','is a legal record and supports continuity of care','is for billing only','impresses supervisors'], 1),
('Operations', 'Which is a HIPAA-permitted disclosure?', array['posting patient details on social media','sharing patient information with the receiving hospital for treatment','telling a friend','discussing it in a public elevator'], 1),
('Operations', 'Medical direction consisting of protocols and standing orders is called:', array['online (direct)','offline (indirect)','verbal only','none of these'], 1),
('Operations', 'At a multi-casualty incident, the primary purpose of the Incident Command System (ICS) is to:', array['assign blame','organize and coordinate resources and personnel','replace triage','speed up billing'], 1);
