-- ---------------------------------------------------------------------------
-- Exam bank corrections, from the 2026-08-10 reviewer report.
--
-- GENERATED by scripts/gen-exam-fixes.mjs — edit that, not this.
--
-- Keyed on stem text, NOT on row id. exam_questions.id is an identity column
-- and exam_questions_hard.sql renumbers its tier on every re-run, so an
-- id-keyed update would eventually rewrite the wrong question. A stem that no
-- longer matches produces no update and is reported by the pre-flight below.
--
-- Safe to re-run. Applying twice is a no-op: the second pass finds the new stem
-- rather than the old one and matches nothing.
--
-- The reviewer's numbering is carried in comments for traceability only. It was
-- verified against this bank (seed row n = id n+120, hard row n = id n+240) but
-- nothing in this file depends on it.
-- ---------------------------------------------------------------------------

begin;

create temp table exam_fix (
  ref        int,
  old_stem   text primary key,
  new_stem   text,
  new_options text[],
  new_answer int
) on commit drop;

insert into exam_fix (ref, old_stem, new_stem, new_options, new_answer) values
  -- 217: Ratio expressions are a recognized medication-error risk (ISMP). Metric concentration instead.
  (217, 'Order: give 1 mg. On hand: 1 mg in 10 mL (1:10,000). You administer:', 'Order: 1 mg. On hand: epinephrine 0.1 mg/mL. How many mL do you give?', array['1 mL','10 mL','0.1 mL','100 mL'], 1),
  -- 252: INCORRECT KEY. E3 + V4 + M5 = 12, not 13.
  (252, 'A patient opens their eyes to voice, is confused, and localizes pain. Their Glasgow Coma Score is:', 'A patient opens their eyes to voice, is confused, and localizes pain. Their Glasgow Coma Score is:', array['12','15','9','11'], 0),
  -- 291: Ratio expressions are a recognized medication-error risk (ISMP).
  (291, 'A 1:10,000 epinephrine concentration contains:', 'Epinephrine 0.1 mg/mL contains:', array['1 mg in 1 mL','1 mg in 10 mL','10 mg in 1 mL','1 mg in 100 mL'], 1),
  -- 293: The old arithmetic was right but 1,000 gtt/min is not a countable rate.
  (293, 'Infuse 500 mL over 30 minutes with a 60 gtt/mL set. The drip rate is:', 'Infuse 500 mL over 4 hours with a 60 gtt/mL set. The drip rate is:', array['125 gtt/min','250 gtt/min','60 gtt/min','500 gtt/min'], 0),
  -- 126: Actual FiO₂ depends on seal, reservoir inflation and minute ventilation.
  (126, 'A non-rebreather mask at 12–15 L/min delivers an approximate FiO₂ of:', 'A non-rebreather mask at 12–15 L/min may deliver an approximate FiO₂ of:', array['about 24 to 28%','about 35 to 40%','about 44 to 60%','about 80 to 95%'], 3),
  -- 140: Avoid declaring 120/80 "normal"; units added.
  (140, 'A normal adult blood pressure is approximately:', 'A typical resting adult blood pressure is approximately:', array['about 90/60 mmHg','about 120/80 mmHg','about 160/100 mmHg','about 200/120 mmHg'], 1),
  -- 147: Distal is defined relative to the point of attachment, not to "the trunk".
  (147, '"Distal" means:', '"Distal" means:', array['nearer to the midline of the body','farther from the point of attachment','closer to the head than the trunk','toward the front surface of the body'], 1),
  -- 165: "Classic" overstates how reliably ACS presents this way.
  (165, 'Classic acute coronary syndrome presents as:', 'A common concerning presentation of acute coronary syndrome is:', array['sharp pain that eases with movement','substernal pressure radiating to the arm','pain only when the chest is pressed','pain isolated to one leg'], 1),
  -- 180: Key on position of comfort rather than a mandated upright position.
  (180, 'The best position for a conscious patient in severe respiratory distress (no trauma) is:', 'The best position for a conscious patient in severe respiratory distress (no trauma) is:', array['lying flat on the back throughout','head-down (Trendelenburg) positioning','a position of comfort, usually upright','lying face-down (prone) for transport'], 2),
  -- 182: Prenotification and destination choice matter, not transport speed alone.
  (182, 'Outcome in an ischemic stroke depends most on:', 'Outcome in an ischemic stroke depends most on:', array['high-flow oxygen given throughout transport','recognition, prenotification, and rapid transport','lowering the blood pressure before transport','aspirin given before arrival at hospital'], 1),
  -- 185: Respiratory depression is the defining feature; pupils are supportive but not required.
  (185, 'Suspected opioid overdose presents with:', 'Which combination is most consistent with opioid toxicity?', array['dilated pupils with rapid, deep breathing','respiratory depression with small pupils','hypertension with generalized seizure activity','a sweet, fruity odor noted on the breath'], 1),
  -- 196: Add the unilateral finding and signs of shock.
  (196, 'Tension pneumothorax signs include:', 'Tension pneumothorax signs include:', array['bradycardia with a rising blood pressure','unilateral absent breath sounds with shock','wheezing heard equally through both lungs','relief that increases with every breath'], 1),
  -- 198: "Golden Hour" is not a defensible term.
  (198, 'The "Golden Hour/Period" concept emphasizes:', 'The concept of time-sensitive trauma care emphasizes:', array['scene time can run as needed','minimizing time to surgical care','requiring 60 minutes on scene','delaying transport for assessment'], 1),
  -- 202: Moist sterile dressing plus occlusive cover; organs are not replaced.
  (202, 'An abdominal evisceration should be covered with:', 'An abdominal evisceration should be covered with:', array['dry gauze applied after replacing the organs','a moist sterile dressing under an occlusive cover','a tourniquet placed around the abdomen itself','nothing at all until arrival at the hospital'], 1),
  -- 234: Standard of care turns on similar training AND similar circumstances.
  (234, '"Standard of care" is best defined as:', '"Standard of care" is best defined as:', array['whatever the individual provider prefers','what a similarly trained provider would do','only what hospital policy happens to say','only what the patient asks to have done'], 1),
  -- 235: The receiving provider has to accept care for the handoff to end the duty.
  (235, 'Abandonment occurs when a provider:', 'Abandonment occurs when a provider:', array['hands off to an equal level with a report','stops care without a handoff that is accepted','declines to enter a clearly unsafe scene','completes thorough and accurate documentation'], 1),
  -- 237: "Most important" is not defensible; documentation is clinical as well as legal.
  (237, 'The most important reason for accurate documentation is that it:', 'Accurate documentation matters chiefly because it:', array['helps to pass the time on a long shift','creates the clinical and legal record of care','is used only for billing and reimbursement','makes a good impression on the supervisors'], 1),
  -- 239: "None of these" replaced with a plausible distractor.
  (239, 'Medical direction consisting of protocols and standing orders is called:', 'Medical direction consisting of protocols and standing orders is called:', array['online (direct) medical direction','offline (indirect) medical direction','verbal orders given by radio','concurrent medical direction'], 1),
  -- 240: Every option repeated the stem’s "to".
  (240, 'At a multi-casualty incident, the primary purpose of the Incident Command System (ICS) is to:', 'At a multi-casualty incident, the primary purpose of the Incident Command System (ICS) is to:', array['assign blame after the incident ends','coordinate resources and personnel','replace the patient triage process','speed up billing and reimbursement'], 1),
  -- 249: "Indicates" overstates; units added.
  (249, 'A head-injured patient has BP 190/80, pulse 48, and irregular respirations. This triad indicates:', 'A head-injured patient has BP 190/80 mmHg, pulse 48 beats/min, and irregular respirations. This triad classically suggests:', array['a significant opioid overdose','decompensated hypovolemic shock','rising intracranial pressure','an isolated spinal cord injury'], 2),
  -- 256: Preload is filling/stretch at end-diastole, not returning volume alone.
  (256, 'Preload is best described as the:', 'Preload is best described as the:', array['ventricular filling and stretch at end-diastole','rate at which the ventricle contracts each beat','thickness of the ventricular muscle wall','resistance the ventricle must pump against'], 0),
  -- 259: Lactate accumulation with metabolic acidosis is the accurate description.
  (259, 'When perfusion fails, cells switch to anaerobic metabolism, which produces:', 'When perfusion fails, cells switch to anaerobic metabolism, which produces:', array['additional usable oxygen for the cells','increased lactate and metabolic acidosis','excess circulating glucose in the blood','carbon monoxide as a waste by-product'], 1),
  -- 265: "Indicates" overstates a triad that is often incomplete.
  (265, 'Beck''s triad — hypotension, distended neck veins, muffled heart tones — indicates:', 'Beck''s triad — hypotension, distended neck veins, muffled heart tones — classically suggests:', array['pulmonary embolism','cardiogenic shock','tension pneumothorax','cardiac tamponade'], 3),
  -- 269: "Without benefit" is too absolute — a small trial may be reasonable in some presentations.
  (269, 'A patient in cardiogenic shock is hypotensive with crackles throughout. Large fluid boluses are hazardous because they:', 'A patient in cardiogenic shock is hypotensive with crackles throughout. Large fluid boluses are hazardous because they:', array['slow the heart rate down too far','can worsen the pulmonary edema further','raise the blood glucose very sharply','constrict the coronary arteries further'], 1),
  -- 287: Absence of expected tachycardia is the discriminating feature; "peripheries" to "extremities".
  (287, 'Neurogenic shock is distinguished from hypovolemic shock chiefly by:', 'Neurogenic shock is distinguished from hypovolemic shock chiefly by:', array['cool, clammy extremities with marked pallor','warm skin without the expected tachycardia','a rapid, thready pulse with cool extremities','a narrowed pulse pressure and strong thirst'], 1),
  -- 303: Blood pressure is maintained until late decompensation.
  (303, 'Compared with adults, children compensate for blood loss by:', 'Compared with adults, children compensate for blood loss by:', array['showing no measurable change in vital signs','letting the blood pressure fall very early','raising rate and tone, with pressure falling late','slowing the heart rate down instead of rising'], 2),
  -- 245: US spelling: laboured.
  (245, 'CPAP would be contraindicated in a patient who:', 'CPAP would be contraindicated in a patient who:', array['has wheezing in all fields','has a long history of COPD','is anxious with labored breathing','is hypotensive and obtunded'], 3),
  -- 264: US spelling: localises.
  (264, 'ST elevation in II, III and aVF localises the infarct to the:', 'ST elevation in II, III and aVF localizes the infarct to the:', array['anterior wall','inferior wall','lateral wall','septal wall'], 1),
  -- 266: US spelling: centres.
  (266, 'A pulseless patient shows an organized rhythm on the monitor. Management centres on:', 'A pulseless patient shows an organized rhythm on the monitor. Management centers on:', array['synchronized cardioversion','withholding further compressions','immediate defibrillation attempts','CPR and reversible-cause treatment'], 3);

-- Pre-flight. Anything listed here was NOT applied, and says which case it is:
-- 'already applied' is the expected result of a second run; 'NOT FOUND' means
-- the bank does not contain that stem and the correction needs a human.
select f.ref,
       case when exists (select 1 from public.exam_questions e where e.stem = f.new_stem)
            then 'already applied' else 'NOT FOUND - needs review' end as state,
       f.old_stem
from exam_fix f
where not exists (select 1 from public.exam_questions e where e.stem = f.old_stem)
order by f.ref;

-- Apply.
update public.exam_questions e
   set stem    = f.new_stem,
       options = f.new_options,
       answer  = f.new_answer
  from exam_fix f
 where e.stem = f.old_stem;

-- Retire, never delete: exam_attempts.question_ids holds bare ids with no
-- foreign key, so a delete silently orphans every historical attempt that
-- served the item. Deactivating drops it from future draws instead.
-- 123: Current AHA wording is one breath every 6 seconds.
update public.exam_questions set active = false where stem = 'For an adult in respiratory arrest with a pulse, deliver one breath every:';
-- 162: Depth has an upper bound (2.4 in / 6 cm), which "at least 2 inches" omits. Ranges keep the bound without making the key the longest option.
update public.exam_questions set active = false where stem = 'Adult compression depth is at least:';
-- 166: "Recent erectile-dysfunction medication" is too vague — the exclusion interval differs by drug.
update public.exam_questions set active = false where stem = 'Before assisting a patient with prescribed nitroglycerin, a key contraindication to check is:';
-- 173: A completely silent MI is also possible, so the old distractor D was defensible. Replaced with something clearly unrelated.
update public.exam_questions set active = false where stem = 'In women, the elderly, and diabetics, an MI may present as:';
-- 176: As written, oral glucose and IV dextrose were both defensible for an AEMT.
update public.exam_questions set active = false where stem = 'Treatment for a conscious hypoglycemic patient who can swallow is:';
-- 197: Three-sided improvised seals are no longer the preferred general answer (2024 AHA/Red Cross First Aid Guidelines).
update public.exam_questions set active = false where stem = 'An open ("sucking") chest wound is initially covered with:';
-- 203: Dangerous bleeding must not be identified by color.
update public.exam_questions set active = false where stem = 'The most immediately life-threatening bleeding to control is:';
-- 204: The keyed option merely repeated the stem.
update public.exam_questions set active = false where stem = 'A burn that is dry, white/leathery or charred, and painless is:';
-- 228: Implies immediate compressions for any newborn HR below 60. Adding the ventilation qualifier fixes that but then duplicates the scenario version of the same fact, which is the better item — so this one goes.
update public.exam_questions set active = false where stem = 'Newborn resuscitation adds chest compressions if the heart rate is below:';
-- 232: A competent patient cannot be REQUIRED to sign. The old key made a signature the obligation.
update public.exam_questions set active = false where stem = 'A competent adult refusing care must be informed of the risks and:';
-- 236: Technique alone does not make a heavy dependent-patient lift safe (OSHA safe patient handling).
update public.exam_questions set active = false where stem = 'When lifting a heavy patient, you should:';
-- 242: A sudden near-zero value can also reflect disconnection or equipment failure, not only tube placement.
update public.exam_questions set active = false where stem = 'In an intubated patient, end-tidal CO₂ suddenly drops to near zero. Your first action is to:';
-- 247: "Ear level to the sternum" is anatomically imprecise.
update public.exam_questions set active = false where stem = 'To improve bag-mask ventilation in a markedly obese patient, position them:';
-- 262: Inferior location alone does not establish clinically important RV preload dependence.
update public.exam_questions set active = false where stem = 'A patient with an inferior STEMI becomes hypotensive after nitroglycerin. The most likely explanation is:';
-- 267: Without a pulse qualifier, an organized narrow rhythm is PEA, not a cardioversion indication.
update public.exam_questions set active = false where stem = 'A patient in narrow-complex tachycardia at 190 is hypotensive and confused. The indicated treatment is:';
-- 271: "First priority" is airway/breathing/circulation, which made the keyed answer arguable.
update public.exam_questions set active = false where stem = 'The first priority in managing diabetic ketoacidosis in the prehospital setting is:';
-- 273: A universal 0.3 mg adult answer is not defensible across guidelines; ratio notation replaced with mg/mL.
update public.exam_questions set active = false where stem = 'The adult intramuscular epinephrine dose for anaphylaxis is:';
-- 278: Beta-blocker overdose treatment is high-dose IV therapy, outside AEMT scope. Kansas authorizes glucagon IM/IN for hypoglycemia.
update public.exam_questions set active = false where stem = 'Glucagon is used in beta-blocker overdose because it:';
-- 279: Avoid implying routine oxygen regardless of saturation.
update public.exam_questions set active = false where stem = 'A patient with a GI bleed is pale, tachycardic and hypotensive. The immediate priority is:';
-- 281: Permissive hypotension is not a universal hemorrhage target.
update public.exam_questions set active = false where stem = 'Permissive hypotension in uncontrolled hemorrhage aims to:';
-- 282: Vital signs cannot reliably determine an individual patient’s exact percentage of blood loss.
update public.exam_questions set active = false where stem = 'An adult with a heart rate of 130, respirations of 32, and confusion has lost approximately:';
-- 288: Needle decompression is not a Kansas AEMT-authorized activity (K.S.A. 65-6120), and item 196 already tests recognition of tension pneumothorax.
update public.exam_questions set active = false where stem = 'Needle decompression for tension pneumothorax is performed at the:';

-- ----- verification --------------------------------------------------------

-- 1. Every correction landed. Expect zero rows.
select f.ref, f.new_stem
from exam_fix f
where not exists (select 1 from public.exam_questions e where e.stem = f.new_stem);

-- 2. The two corrected keys the reviewer called out by value.
select id, stem, options[answer + 1] as keyed_answer
from public.exam_questions
where stem like 'A patient opens their eyes to voice%'      -- expect 12
   or stem like 'Infuse 500 mL over 4 hours%';              -- expect 125 gtt/min

-- 3. Bank size and the stored answer-position spread. The spread is reported
--    for information only: ExamPage shuffles option order per attempt, seeded
--    on the attempt id, so a candidate never sees the stored positions. It is
--    still worth watching in case that shuffle is ever removed.
select count(*) filter (where active) as active_items,
       count(*) filter (where not active) as retired_items
from public.exam_questions;

select answer, count(*) as items,
       round(100.0 * count(*) / sum(count(*)) over (), 1) as pct
from public.exam_questions
where active
group by answer
order by answer;

commit;
