-- ---------------------------------------------------------------------------
-- NEOP selection exam — INSTALL EVERYTHING, IN ORDER.
--
-- Paste the whole file into the Supabase SQL Editor and run it once. It is
-- safe to run again: every statement in it is written to be re-runnable, the
-- question bank upserts on each item’s code rather than reloading, and items no
-- longer in the bank are retired instead of deleted, so an attempt already on
-- record is never orphaned.
--
-- It contains, in this order and unchanged:
--
--   1. migrations/2026-08-18-neop-selection-exam.sql
--   2. migrations/2026-08-19-neop-exam-sections-and-clock.sql
--   3. neop_exam_questions_seed.sql
--
-- GENERATED by scripts/gen-neop-exam.mjs. Do not edit this file — edit those
-- three, and run: npm run gen:neop
--
-- IF THE APP STILL SAYS THE EXAM IS UNAVAILABLE after this runs, PostgREST is
-- holding a stale schema cache. The last statement in this file reloads it; if
-- you are pasting only part of the file, run this on its own:
--
--   notify pgrst, ’reload schema’;
-- ---------------------------------------------------------------------------

-- ---------------------------------------------------------------------------
-- The NEOP selection exam: a second program on the exam engine.
--
-- WHY A SECOND PROGRAM RATHER THAN A SECOND SET OF TABLES. Everything that
-- makes the AEMT exam trustworthy is in the plumbing, not the questions: the
-- bank and the key never leave the database, grading happens server-side, the
-- clock is enforced where a candidate cannot edit it, one draw per person ever,
-- an attempt is voided rather than deleted, and the signed integrity statement
-- is stored with a hash of its own wording. A parallel set of tables for the
-- new-hire exam would be a second copy of all of that, and the copy would be
-- the one that rots. So exam_questions and exam_attempts both grow a `program`
-- column and the two functions take a program argument.
--
-- WHAT IS ACTUALLY NEW, and it is not cosmetic:
--
--   SECTIONS. The NEOP exam is three sections that are not interchangeable —
--   patient care, understanding of the Kansas City interfacility operation,
--   and what the candidate actually wants from the job. The draw is stratified
--   so every candidate gets the same shape of exam rather than whatever 36
--   random items happened to come up.
--
--   UNSCORED ITEMS. The preference section has no answer key, and cannot be
--   given one: `answer` becomes nullable, `scored` is GENERATED from it, and
--   exam_submit skips anything that is not scored. An item with no key cannot
--   be accidentally scored against a candidate, because there is nothing in
--   the row to score it against.
--
--   `code`. A stable identifier per item. The AEMT bank has none, which is why
--   its corrections file has to match on stem text and says so at length. The
--   interview probes for the preference items are keyed to these codes.
--
-- SAFE TO RE-RUN. One transaction: a half-applied state here would be a
-- stratified draw against a bank with no sections, which fails at the moment a
-- candidate presses Start.
--
-- The AEMT exam is untouched by design. Existing rows default to
-- program = ’aemt’; its draw, cutoff, clock and one-attempt rule behave exactly
-- as before, and an attempt already in flight is unaffected.
-- ---------------------------------------------------------------------------

begin;


-- ============================================================================
-- 1. The bank grows a program, sections, stable codes, and unscored items
-- ============================================================================

alter table public.exam_questions
  add column if not exists program text not null default 'aemt',
  add column if not exists section text,
  add column if not exists code text;

alter table public.exam_questions drop constraint if exists exam_questions_program_check;
alter table public.exam_questions add constraint exam_questions_program_check
  check (program in ('aemt', 'neop'));

alter table public.exam_questions drop constraint if exists exam_questions_section_check;
alter table public.exam_questions add constraint exam_questions_section_check
  check (section is null or section in ('clinical', 'operations', 'fit'));

-- A NEOP item without a section cannot be drawn — the draw is per section —
-- so it would sit in the bank looking loaded and never be served.
alter table public.exam_questions drop constraint if exists exam_questions_neop_has_section;
alter table public.exam_questions add constraint exam_questions_neop_has_section
  check (program <> 'neop' or section is not null);

-- The key becomes optional, and its absence is what makes an item unscored.
alter table public.exam_questions alter column answer drop not null;

-- Unscored items live in the preference section and nowhere else, in both
-- directions: a keyed preference item would be scoring somebody’s stated
-- ambitions, and an unkeyed item anywhere else is a question that quietly
-- counts for nothing.
alter table public.exam_questions drop constraint if exists exam_questions_unscored_is_fit;
alter table public.exam_questions add constraint exam_questions_unscored_is_fit
  check ((answer is null) = (section is not distinct from 'fit'));

-- Generated, not maintained. There is no way to have a row whose `scored` flag
-- disagrees with whether it has an answer.
alter table public.exam_questions
  add column if not exists scored boolean
  generated always as (answer is not null) stored;

create unique index if not exists exam_questions_code_idx
  on public.exam_questions (code) where code is not null;

create index if not exists exam_questions_draw_idx
  on public.exam_questions (program, section) where active;


-- ============================================================================
-- 2. Attempts record which exam was sat
-- ============================================================================

alter table public.exam_attempts
  add column if not exists program text not null default 'aemt';

alter table public.exam_attempts drop constraint if exists exam_attempts_program_check;
alter table public.exam_attempts add constraint exam_attempts_program_check
  check (program in ('aemt', 'neop'));

-- One attempt per email PER PROGRAM. Without the program in the key, an
-- internal EMT who sat the AEMT selection exam could never sit the new-hire
-- exam, and the failure would look like ”you have already taken this” to
-- somebody who has not.
drop index if exists public.exam_attempts_one_submitted_per_email;
create unique index if not exists exam_attempts_one_submitted_per_email_program
  on public.exam_attempts (email, program)
  where submitted_at is not null and voided_at is null;

create index if not exists exam_attempts_program_idx on public.exam_attempts (program);


-- ============================================================================
-- 3. exam_start — per-program configuration and a stratified draw
-- ============================================================================
-- The old five-argument signature is DROPPED rather than left in place.
-- Creating the six-argument version beside it would leave two overloads, and
-- every call would fail with ”function exam_start(unknown, unknown) is not
-- unique” — the exact failure the migration README warns about. p_program
-- defaults to ’aemt’, so a browser still running the previous build calls the
-- new function successfully and gets the AEMT exam it asked for.

drop function if exists public.exam_start(text, text, boolean, text, text);

create or replace function public.exam_start(
  p_name text,
  p_email text,
  p_attested boolean default null,
  p_signature text default null,
  p_attestation_hash text default null,
  p_program text default 'aemt'
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_email   text := lower(trim(p_email));
  v_name    text := trim(p_name);
  v_sign    text := nullif(trim(coalesce(p_signature, '')), '');
  v_program text := coalesce(nullif(trim(p_program), ''), 'aemt');
  -- Per-program configuration. The AEMT row is the existing behavior,
  -- unchanged: 17 August cutoff, 25 minutes, 50 items drawn at random.
  --
  -- NEOP has NO CUTOFF because hiring is rolling — a new-hire exam that closes
  -- on a date is an exam that silently stops working for every applicant after
  -- it, which is worse than any deadline it was meant to enforce.
  v_cutoff  timestamptz;
  v_limit   int;
  v_draw    int;
  v_clin    int;
  v_ops     int;
  v_have    int;
  v_attempt public.exam_attempts;
  v_qids    bigint[];
  v_total   int;
  v_questions jsonb;
begin
  if v_program not in ('aemt', 'neop') then
    return jsonb_build_object('error', 'Unknown exam.');
  end if;
  if v_name = '' or v_email = '' then
    return jsonb_build_object('error', 'Name and email are required.');
  end if;

  if v_program = 'aemt' then
    v_cutoff := '2026-08-17 17:00:00-05';   -- Aug 17, 5 PM Central
    v_limit  := 25 * 60;
    v_draw   := 50;
  else
    v_cutoff := null;                       -- rolling
    v_limit  := 30 * 60;
    v_clin   := 12;
    v_ops    := 16;                         -- every fit item is served
  end if;

  if v_cutoff is not null and now() > v_cutoff then
    return jsonb_build_object('error', 'closed');
  end if;

  select * into v_attempt from public.exam_attempts a
    where a.email = v_email
      and a.program = v_program
      and a.voided_at is null          -- a reset attempt no longer counts
    order by a.started_at desc limit 1;

  if found then
    if v_attempt.submitted_at is not null then
      return jsonb_build_object('error', 'already_taken');
    end if;
    if now() > v_attempt.started_at + make_interval(secs => v_attempt.limit_seconds) then
      return jsonb_build_object('error', 'expired');
    end if;
    v_qids := v_attempt.question_ids;
  else
    if v_program = 'aemt' then
      select array_agg(id) into v_qids
        from (select id from public.exam_questions
               where active and program = 'aemt'
               order by random() limit v_draw) s;
      if v_qids is null or array_length(v_qids, 1) < v_draw then
        return jsonb_build_object('error', 'bank_too_small');
      end if;
    else
      -- Stratified: a fixed number from each scored section, then EVERY
      -- preference item. The preference items are not sampled — an interviewer
      -- comparing two candidates needs them to have answered the same
      -- questions, and a random subset of eleven takes that away.
      select count(*) into v_have from public.exam_questions
        where active and program = 'neop' and section = 'clinical';
      if v_have < v_clin then return jsonb_build_object('error', 'bank_too_small'); end if;
      select count(*) into v_have from public.exam_questions
        where active and program = 'neop' and section = 'operations';
      if v_have < v_ops then return jsonb_build_object('error', 'bank_too_small'); end if;
      select count(*) into v_have from public.exam_questions
        where active and program = 'neop' and section = 'fit';
      if v_have < 1 then return jsonb_build_object('error', 'bank_too_small'); end if;

      with picked as (
        select id, 1 as sect_ord from (
          select id from public.exam_questions
           where active and program = 'neop' and section = 'clinical'
           order by random() limit v_clin) c
        union all
        select id, 2 from (
          select id from public.exam_questions
           where active and program = 'neop' and section = 'operations'
           order by random() limit v_ops) o
        union all
        select id, 3 from public.exam_questions
         where active and program = 'neop' and section = 'fit'
      )
      select array_agg(id order by sect_ord, random()) into v_qids from picked;
    end if;

    -- Only keyed items count toward the score, so only keyed items count
    -- toward the total. Otherwise a candidate who answers every scored item
    -- correctly is recorded at 78%.
    select count(*) into v_total from public.exam_questions
      where id = any(v_qids) and scored;
    if coalesce(v_total, 0) = 0 then
      return jsonb_build_object('error', 'bank_too_small');
    end if;

    insert into public.exam_attempts (
      name, email, question_ids, total, limit_seconds, program,
      attested, signature, attested_at, attestation_hash)
      values (
        v_name, v_email, v_qids, v_total, v_limit, v_program,
        p_attested, v_sign,
        case when p_attested is true then now() else null end,
        nullif(trim(coalesce(p_attestation_hash, '')), ''))
      returning * into v_attempt;
  end if;

  select jsonb_agg(
           jsonb_build_object(
             'id', q.id, 'domain', q.domain, 'stem', q.stem, 'options', q.options,
             'section', q.section, 'scored', q.scored)
           order by array_position(v_qids, q.id))
    into v_questions
    from public.exam_questions q
    where q.id = any(v_qids);

  return jsonb_build_object(
    'attemptId', v_attempt.id,
    'startedAt', v_attempt.started_at,
    'limitSeconds', v_attempt.limit_seconds,
    'program', v_attempt.program,
    'questions', coalesce(v_questions, '[]'::jsonb));
end;
$$;

revoke all on function public.exam_start(text, text, boolean, text, text, text) from public;
grant execute on function public.exam_start(text, text, boolean, text, text, text) to anon, authenticated;


-- ============================================================================
-- 4. exam_submit — grade the keyed items, keep the rest
-- ============================================================================
-- Unscored responses are STORED and not graded. They are the whole point of
-- the preference section: the interviewer reads them beside the candidate’s
-- name, and nothing about them touches the score.

create or replace function public.exam_submit(p_attempt uuid, p_responses jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_grace constant int := 60;
  v_attempt public.exam_attempts;
  v_score int := 0;
  v_qid bigint;
  v_ans int;
  v_chosen int;
begin
  select * into v_attempt from public.exam_attempts where id = p_attempt;
  if not found then
    return jsonb_build_object('error', 'Attempt not found.');
  end if;
  if v_attempt.voided_at is not null then
    return jsonb_build_object('error', 'voided');
  end if;
  if v_attempt.submitted_at is not null then
    return jsonb_build_object('error', 'already_submitted');
  end if;
  if now() > v_attempt.started_at
             + make_interval(secs => v_attempt.limit_seconds + v_grace) then
    return jsonb_build_object('error', 'expired');
  end if;

  foreach v_qid in array v_attempt.question_ids loop
    select answer into v_ans from public.exam_questions where id = v_qid;
    -- No key, no marks. A preference item cannot be scored even by accident.
    if v_ans is null then
      continue;
    end if;
    v_chosen := nullif(p_responses ->> v_qid::text, '')::int;
    if v_chosen is not null and v_chosen = v_ans then
      v_score := v_score + 1;
    end if;
  end loop;

  update public.exam_attempts
     set submitted_at = now(),
         responses = p_responses,
         score = v_score,
         percent = round(100.0 * v_score / nullif(v_attempt.total, 0), 1)
   where id = p_attempt;
  return jsonb_build_object('ok', true);
end;
$$;

revoke all on function public.exam_submit(uuid, jsonb) from public;
grant execute on function public.exam_submit(uuid, jsonb) to anon, authenticated;

commit;


-- ============================================================================
-- Load the questions
-- ============================================================================
-- Then run supabase/neop_exam_questions_seed.sql, which loads only
-- program = ’neop’ rows and leaves the AEMT bank alone.


-- ============================================================================
-- Revert
-- ============================================================================
-- Removes the NEOP program and restores the previous behavior. It deletes the
-- NEOP bank and any NEOP attempts with it, so take a copy of exam_attempts
-- first if anybody has sat it.
--
-- begin;
-- delete from public.exam_attempts where program = ’neop’;
-- delete from public.exam_questions where program = ’neop’;
-- alter table public.exam_questions
--   drop constraint if exists exam_questions_unscored_is_fit,
--   drop constraint if exists exam_questions_neop_has_section,
--   drop constraint if exists exam_questions_section_check,
--   drop constraint if exists exam_questions_program_check,
--   drop column if exists scored,
--   drop column if exists code,
--   drop column if exists section,
--   drop column if exists program;
-- alter table public.exam_questions alter column answer set not null;
-- drop index if exists public.exam_attempts_one_submitted_per_email_program;
-- create unique index if not exists exam_attempts_one_submitted_per_email
--   on public.exam_attempts (email) where submitted_at is not null and voided_at is null;
-- alter table public.exam_attempts
--   drop constraint if exists exam_attempts_program_check,
--   drop column if exists program;
-- -- then re-create exam_start / exam_submit from schema.sql as they stood before.
-- commit;


-- ---------------------------------------------------------------------------
-- NEOP selection exam: ask what they want BEFORE we spend a quarter of an hour
-- telling them what we want, and give the sitting five more minutes.
--
-- Follows 2026-08-18-neop-selection-exam.sql, which built the exam. Nothing
-- structural changes here — one function is replaced.
--
-- WHY THE ORDER MATTERS. The sections were served patient care, our operation,
-- preferences. The operations section is sixteen questions whose correct
-- answers all describe what this operation values and what it is wary of:
-- that nobody moves onto a 911 truck by waiting here, that a shift where you
-- used no emergency skills is a good day, that we would rather hear it now if
-- scene work is what somebody wants. A candidate reaches the preference items
-- having just been coached, at length and with a score attached, on the
-- answers we would like.
--
-- So the preference items now come second: patient care first as a neutral
-- warm-up that gives nothing away, then what they want, then the operations
-- section. The briefing still precedes all of it and still says plainly what
-- this job is not — that is a deliberate trade, because letting somebody
-- withdraw before the interview is worth more than a clean measurement, and it
-- is why those items lean on what an applicant has already done rather than on
-- what they say they intend.
--
-- AND THE CLOCK. 28 scored items and 13 preference items in 30 minutes was
-- tight enough that a slow reader would be answering the last operations items
-- against a timer, which measures reading speed rather than comprehension. 35.
--
-- The AEMT exam is untouched: its branch of this function is unchanged, and an
-- attempt already in flight keeps the allowance recorded on it when it started.
--
-- Safe to re-run.
-- ---------------------------------------------------------------------------

begin;

create or replace function public.exam_start(
  p_name text,
  p_email text,
  p_attested boolean default null,
  p_signature text default null,
  p_attestation_hash text default null,
  p_program text default 'aemt'
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_email   text := lower(trim(p_email));
  v_name    text := trim(p_name);
  v_sign    text := nullif(trim(coalesce(p_signature, '')), '');
  v_program text := coalesce(nullif(trim(p_program), ''), 'aemt');
  -- Per-program configuration. The AEMT row is the existing behavior,
  -- unchanged: 17 August cutoff, 25 minutes, 50 items drawn at random.
  --
  -- NEOP has NO CUTOFF because hiring is rolling — a new-hire exam that closes
  -- on a date is an exam that silently stops working for every applicant after
  -- it, which is worse than any deadline it was meant to enforce.
  v_cutoff  timestamptz;
  v_limit   int;
  v_draw    int;
  v_clin    int;
  v_ops     int;
  v_have    int;
  v_attempt public.exam_attempts;
  v_qids    bigint[];
  v_total   int;
  v_questions jsonb;
begin
  if v_program not in ('aemt', 'neop') then
    return jsonb_build_object('error', 'Unknown exam.');
  end if;
  if v_name = '' or v_email = '' then
    return jsonb_build_object('error', 'Name and email are required.');
  end if;

  if v_program = 'aemt' then
    v_cutoff := '2026-08-17 17:00:00-05';   -- Aug 17, 5 PM Central
    v_limit  := 25 * 60;
    v_draw   := 50;
  else
    v_cutoff := null;                       -- rolling
    v_limit  := 35 * 60;
    v_clin   := 12;
    v_ops    := 16;                         -- every preference item is served
  end if;

  if v_cutoff is not null and now() > v_cutoff then
    return jsonb_build_object('error', 'closed');
  end if;

  select * into v_attempt from public.exam_attempts a
    where a.email = v_email
      and a.program = v_program
      and a.voided_at is null          -- a reset attempt no longer counts
    order by a.started_at desc limit 1;

  if found then
    if v_attempt.submitted_at is not null then
      return jsonb_build_object('error', 'already_taken');
    end if;
    if now() > v_attempt.started_at + make_interval(secs => v_attempt.limit_seconds) then
      return jsonb_build_object('error', 'expired');
    end if;
    v_qids := v_attempt.question_ids;
  else
    if v_program = 'aemt' then
      select array_agg(id) into v_qids
        from (select id from public.exam_questions
               where active and program = 'aemt'
               order by random() limit v_draw) s;
      if v_qids is null or array_length(v_qids, 1) < v_draw then
        return jsonb_build_object('error', 'bank_too_small');
      end if;
    else
      -- Stratified: a fixed number from each scored section, then EVERY
      -- preference item. The preference items are not sampled — an interviewer
      -- comparing two candidates needs them to have answered the same
      -- questions, and a random subset takes that away.
      --
      -- sect_ord 1/2/3 is patient care, then preferences, then our operation.
      -- See the header: the operations section is the one that tells a
      -- candidate what we want to hear, so it comes after we have asked.
      select count(*) into v_have from public.exam_questions
        where active and program = 'neop' and section = 'clinical';
      if v_have < v_clin then return jsonb_build_object('error', 'bank_too_small'); end if;
      select count(*) into v_have from public.exam_questions
        where active and program = 'neop' and section = 'operations';
      if v_have < v_ops then return jsonb_build_object('error', 'bank_too_small'); end if;
      select count(*) into v_have from public.exam_questions
        where active and program = 'neop' and section = 'fit';
      if v_have < 1 then return jsonb_build_object('error', 'bank_too_small'); end if;

      with picked as (
        select id, 1 as sect_ord from (
          select id from public.exam_questions
           where active and program = 'neop' and section = 'clinical'
           order by random() limit v_clin) c
        union all
        select id, 2 from public.exam_questions
         where active and program = 'neop' and section = 'fit'
        union all
        select id, 3 from (
          select id from public.exam_questions
           where active and program = 'neop' and section = 'operations'
           order by random() limit v_ops) o
      )
      select array_agg(id order by sect_ord, random()) into v_qids from picked;
    end if;

    -- Only keyed items count toward the score, so only keyed items count
    -- toward the total. Otherwise a candidate who answers every scored item
    -- correctly is recorded at 68%.
    select count(*) into v_total from public.exam_questions
      where id = any(v_qids) and scored;
    if coalesce(v_total, 0) = 0 then
      return jsonb_build_object('error', 'bank_too_small');
    end if;

    insert into public.exam_attempts (
      name, email, question_ids, total, limit_seconds, program,
      attested, signature, attested_at, attestation_hash)
      values (
        v_name, v_email, v_qids, v_total, v_limit, v_program,
        p_attested, v_sign,
        case when p_attested is true then now() else null end,
        nullif(trim(coalesce(p_attestation_hash, '')), ''))
      returning * into v_attempt;
  end if;

  select jsonb_agg(
           jsonb_build_object(
             'id', q.id, 'domain', q.domain, 'stem', q.stem, 'options', q.options,
             'section', q.section, 'scored', q.scored)
           order by array_position(v_qids, q.id))
    into v_questions
    from public.exam_questions q
    where q.id = any(v_qids);

  return jsonb_build_object(
    'attemptId', v_attempt.id,
    'startedAt', v_attempt.started_at,
    'limitSeconds', v_attempt.limit_seconds,
    'program', v_attempt.program,
    'questions', coalesce(v_questions, '[]'::jsonb));
end;
$$;

revoke all on function public.exam_start(text, text, boolean, text, text, text) from public;
grant execute on function public.exam_start(text, text, boolean, text, text, text) to anon, authenticated;

commit;

-- ---------------------------------------------------------------------------
-- Then re-run supabase/neop_exam_questions_seed.sql: the patient-care section
-- has been rewritten to newly-qualified-EMT scope and the preference items
-- replaced. The seed upserts on `code` and retires what is no longer in the
-- bank, so no attempt already on record is orphaned.
--
-- Revert: re-create exam_start from the 2026-08-18 migration.
-- ---------------------------------------------------------------------------


-- ---------------------------------------------------------------------------
-- NEOP selection exam question bank (97 items: 42 clinical, 42 operations, 13 fit).
--
-- GENERATED by scripts/gen-neop-exam.mjs from scripts/neop-exam-bank.mjs.
-- Do not hand-edit: edit the bank and run `npm run check:neop`, which
-- regenerates nothing but tells you this file has drifted.
--
-- Requires the 2026-08-18-neop-selection-exam.sql migration (or a schema.sql
-- new enough to contain the program/section/code columns).
--
-- SAFE TO RE-RUN, and safe to re-run against a live exam. It upserts on
-- `code` and never deletes: an id already recorded in
-- exam_attempts.question_ids keeps its row and its meaning. Items removed from
-- the bank are retired (active = false) rather than dropped, so a historical
-- attempt still resolves to the question it actually asked.
--
-- The AEMT bank is untouched — every statement here is fenced to
-- program = ’neop’.
--
-- The preference items carry answer = null on purpose. That is what makes them
-- unscored: the database generates `scored` from it and exam_submit skips
-- them. Giving one of them a key would score a candidate on what they want.
-- ---------------------------------------------------------------------------

insert into public.exam_questions (program, section, code, domain, stem, options, answer, active)
select 'neop', v.section, v.code, v.domain, v.stem, v.options, v.answer, true
from (values
('clinical', 'clin-scene-safety', 'Assessment', 'You arrive to find a scene that may not be safe. Your first priority is:', array['reaching the patient quickly','your own safety and your partner’s','a set of vital signs','a report to dispatch'], 1),
('clinical', 'clin-bsi', 'Assessment', 'Standard precautions — gloves and other personal protective equipment — are used:', array['on every patient contact','only where an infection is known about','only where there is visible blood','at the crew member’s discretion'], 0),
('clinical', 'clin-avpu', 'Assessment', 'AVPU is used to assess:', array['pupil size and reaction','level of consciousness','skin color and temperature','the severity of pain'], 1),
('clinical', 'clin-adult-hr', 'Assessment', 'A normal resting heart rate for an adult is:', array['40 to 60','60 to 100','100 to 120','120 to 140'], 1),
('clinical', 'clin-unstable-reassess', 'Assessment', 'An unstable patient should be reassessed at least every:', array['5 minutes','15 minutes','30 minutes','once on arrival'], 0),
('clinical', 'clin-trend', 'Assessment', 'Across three sets of vitals your patient’s systolic blood pressure has fallen from 130 to 118 to 104, and the pulse has risen each time. This is:', array['nothing to act on until a reading is actually abnormal','a trend worth acting on and reporting now','an expected response to being moved','a sign the cuff is the wrong size'], 1),
('clinical', 'clin-early-shock', 'Bleeding & shock', 'Early (compensated) shock in an adult typically presents as:', array['a low blood pressure with a slow pulse','a fast pulse and pale, cool skin with a blood pressure still in range','warm, flushed skin with a slow pulse','no change at all until the patient collapses'], 1),
('clinical', 'clin-bleeding-first', 'Bleeding & shock', 'The first action for severe bleeding from an arm or a leg is:', array['elevate the limb','firm direct pressure on the wound','a pressure point above the wound','a cold pack over the dressing'], 1),
('clinical', 'clin-tourniquet', 'Bleeding & shock', 'A tourniquet on a limb is indicated when:', array['any bleeding is seen','direct pressure has failed to control the bleeding','thirty minutes of pressure have passed','the patient is on a blood thinner'], 1),
('clinical', 'clin-airway-first', 'Airway & breathing', 'Your patient becomes unresponsive. Your first action is to:', array['call for orders','check the airway and breathing','note the time','get a blood pressure'], 1),
('clinical', 'clin-opa-gag', 'Airway & breathing', 'An oropharyngeal airway (OPA) should not be used in a patient who:', array['is apneic','still has a gag reflex','is deeply unresponsive','has an oxygen saturation below 90%'], 1),
('clinical', 'clin-npa-size', 'Airway & breathing', 'A nasopharyngeal airway is sized by measuring from the:', array['corner of the mouth to the earlobe','nostril to the earlobe','nose to the sternal notch','lips to the chin'], 1),
('clinical', 'clin-vent-rate', 'Airway & breathing', 'An adult who is not breathing but has a pulse should be ventilated at about one breath every:', array['3 seconds','5 to 6 seconds','10 seconds','15 seconds'], 1),
('clinical', 'clin-chest-rise', 'Airway & breathing', 'The best sign that your ventilations are adequate is:', array['air escaping around the mask','visible chest rise with each breath','the stomach rising with each breath','increasing resistance to each breath'], 1),
('clinical', 'clin-nrb-flow', 'Airway & breathing', 'A non-rebreather mask should be run at a flow rate of:', array['2 L/min','4 to 6 L/min','12 to 15 L/min','25 L/min'], 2),
('clinical', 'clin-hypoxia', 'Airway & breathing', 'Hypoxia is best defined as:', array['too much carbon dioxide in the blood','inadequate oxygen at the tissue level','a raised respiratory rate','a low circulating blood volume'], 1),
('clinical', 'clin-copd-oxygen', 'Airway & breathing', 'A patient with a long history of COPD is clearly hypoxic. You should:', array['withhold oxygen because of the COPD','give oxygen and titrate it to their saturation','give oxygen only if they ask for it','leave the decision to the hospital'], 1),
('clinical', 'clin-pulseox-co', 'Airway & breathing', 'A pulse oximeter can read falsely high in a patient who has:', array['a fever','been exposed to carbon monoxide','received supplemental oxygen','a fast heart rate'], 1),
('clinical', 'clin-position-resp', 'Airway & breathing', 'A conscious patient in respiratory distress, with no trauma, is best positioned:', array['flat on their back','head down','sitting upright','face down'], 2),
('clinical', 'clin-suction', 'Airway & breathing', 'A patient vomits and cannot clear it themselves. Your first action is to:', array['raise the head of the cot and carry on','clear the airway with suction and position the patient to protect it','apply a non-rebreather mask','note the time and tell the receiving nurse'], 1),
('clinical', 'clin-recovery-position', 'Airway & breathing', 'An unresponsive adult is breathing adequately and has no sign of injury. They are best placed:', array['flat on their back','on their side, in the recovery position','sitting fully upright','face down'], 1),
('clinical', 'clin-peds-airway', 'Airway & breathing', 'Compared with an adult, a small child’s airway has:', array['a smaller tongue and a wider airway','a larger tongue and a narrower airway','a stiffer epiglottis','a longer, more rigid trachea'], 1),
('clinical', 'clin-cpr-rate', 'Cardiac arrest', 'Adult chest compressions are delivered at a rate of:', array['60 to 80 per minute','80 to 100 per minute','100 to 120 per minute','140 to 160 per minute'], 2),
('clinical', 'clin-cpr-depth', 'Cardiac arrest', 'Adult chest compressions should be at least:', array['1 inch deep','1.5 inches deep','2 inches deep','3 inches deep'], 2),
('clinical', 'clin-aed', 'Cardiac arrest', 'An AED should be applied to a patient who is:', array['unresponsive with no pulse','unresponsive with a pulse','responsive with chest pain','having a seizure'], 0),
('clinical', 'clin-cpr-quality', 'Cardiac arrest', 'High-quality CPR depends most on:', array['frequent pauses to check for a pulse','full chest recoil and few interruptions','shallow, very fast compressions','breaths given before compressions'], 1),
('clinical', 'clin-glucose-check', 'Medical', 'A patient becomes confused and sweaty. The most rapidly correctable cause to check for is:', array['a stroke','a low blood glucose','a brain tumor','a migraine'], 1),
('clinical', 'clin-oral-glucose', 'Medical', 'A hypoglycemic patient is awake and able to swallow. The appropriate treatment is:', array['nothing by mouth','oral glucose','a large drink of water','waiting for the hospital'], 1),
('clinical', 'clin-anaphylaxis', 'Medical', 'Hives, wheezing and a falling blood pressure shortly after a bee sting indicate:', array['an anxiety attack','anaphylaxis','a fainting episode','a local reaction'], 1),
('clinical', 'clin-stroke-lkw', 'Medical', 'For a patient with stroke signs, the single most important time to establish is:', array['when the family called','when the patient was last known well','when you arrived','when the vital signs were taken'], 1),
('clinical', 'clin-seizure-status', 'Medical', 'A seizure lasting more than five minutes, or repeated seizures without recovery in between, is:', array['a normal febrile seizure','status epilepticus, and an emergency','a fainting episode','expected in anybody with epilepsy'], 1),
('clinical', 'clin-aspirin-why', 'Medical', 'Aspirin is given in suspected cardiac chest pain in order to:', array['relieve the pain','reduce clumping of platelets','slow the heart rate','raise the blood pressure'], 1),
('clinical', 'clin-nitro-check', 'Medical', 'Before assisting a patient with their own prescribed nitroglycerin, an important thing to ask about is:', array['any recent erectile-dysfunction medication','whether they have eaten today','their family history','their tetanus status'], 0),
('clinical', 'clin-spine', 'Trauma', 'A patient has fallen and reports neck pain. While you assess them you should:', array['have them turn their head to test the movement','limit movement of the head and neck','sit them straight up','walk them to the cot'], 1),
('clinical', 'clin-refusal', 'Patient care', 'An alert, oriented adult refuses transport. You should:', array['transport them anyway, for their own good','explain the risks, document the refusal, and respect their decision','leave without saying anything further','have a family member sign for them'], 1),
('clinical', 'clin-heavy-lift', 'Lifting & moving', 'A patient is heavier than the two of you can move safely. You should:', array['move fast, to keep the strain brief','get more hands and the right equipment, even though it takes longer','have the patient take their own weight','drag them across on the bed sheet'], 1),
('clinical', 'clin-straps', 'Lifting & moving', 'A patient is on the cot for transport. The straps should be:', array['all fastened, including the shoulder straps','across the waist only, so they can sit up','left loose on a short trip','fastened only if the patient is unresponsive'], 0),
('clinical', 'clin-confused-safety', 'Lifting & moving', 'You are moving a confused patient. The most important safety measure is:', array['restraining their wrists','rails up, straps secured, and never leaving them unattended','a family member at the head of the cot','sedation before you move'], 1),
('clinical', 'clin-handover', 'Patient care', 'Your verbal report at the hospital should always include:', array['the route you took','the patient, the problem, and anything that changed while they were with you','only what the family told you','nothing — the written report covers it'], 1),
('clinical', 'clin-chart-timing', 'Documentation', 'The best time to write your patient care report is:', array['at the end of the shift, all together','as soon as practical, while the detail is accurate','only if something went wrong','before the call, so it is ready'], 1),
('clinical', 'clin-chart-honest', 'Documentation', 'You realize you missed a set of vital signs. Your report should:', array['record what was actually done, including the gap','estimate the missing set from the readings either side','leave the section blank with no comment','record the later set at the earlier time'], 0),
('clinical', 'clin-equipment-check', 'Equipment', 'Equipment on the truck should be checked:', array['at the start of every shift, before it is needed','when a call comes in for a patient who needs it','weekly','after it has been used'], 0),
('operations', 'ops-primary-work', 'Our operation', 'AMR Kansas City''s primary work is:', array['responding to 911 calls across the metro','moving patients between healthcare facilities','standby cover at public events','air ambulance and flight transport'], 1),
('operations', 'ops-transport-kinds', 'Our operation', 'Alongside hospital-to-hospital work, this operation is also called on for:', array['search and rescue','bariatric transports and long-distance moves well outside the metro','air ambulance transfers','home health visits'], 1),
('operations', 'ops-normal-call', 'Our operation', 'Which of these is a normal call for this operation?', array['a multi-vehicle collision on the highway','an ICU patient moving to a hospital that can do something the sending one cannot','a cardiac arrest called in from a private residence','a stabbing outside a bar at closing time'], 1),
('operations', 'ops-geography', 'Our operation', 'The Kansas City operation works:', array['in Missouri only','in Kansas only','on both sides of the state line, in Missouri and Kansas','anywhere in the two states, dispatched from a single hospital'], 2),
('operations', 'ops-volume', 'Our operation', 'The operation completes roughly how many transports each month?', array['about 100','about 1,000','about 10,000','it varies too much to say'], 1),
('operations', 'ops-already-a-patient', 'Our operation', 'When you arrive at the sending facility, the patient has usually already been:', array['assessed, diagnosed, and started on a treatment plan','discharged from the care of the sending facility','assessed by the crew who transported them in','left for you to work up from the beginning'], 0),
('operations', 'ops-our-responsibility', 'Our operation', 'The briefing describes our responsibility for a patient already on a treatment plan as:', array['driving them safely to the address on the paperwork','to understand that plan, continue it safely, recognize when something changes, and hand the patient over accurately','starting our own treatment plan once the doors close','waiting for the receiving facility to tell us what to do'], 1),
('operations', 'ops-what-could-change', 'Our operation', 'The briefing says the question on this job is usually not "What am I walking into?" but:', array['"How quickly can we clear?"','"What could change during this trip, and am I prepared for it?"','"Who is going to write this chart?"','"Is this transport really necessary?"'], 1),
('operations', 'ops-scene-calls', 'Our operation', 'Day to day, 911 scene calls on this operation are:', array['the majority of the work','a few every shift, mixed in among the transfers','not what the job is made of — the exceptions are event standby and mutual aid when a neighboring 911 system asks','given to crews once they have been released from field training'], 2),
('operations', 'ops-standby-aid', 'Our operation', 'Standby coverage at the Kansas Speedway, and responding on mutual aid when a neighboring 911 system asks for help:', array['are the main work of this operation','both happen, and both are the exception rather than what a shift is made of','are handled by a different company','are how crews transfer onto a 911 operation'], 1),
('operations', 'ops-lights-sirens', 'Our operation', 'Emergency lights and sirens on this operation are:', array['used on most transports','the exception — most transports are made at ordinary road speed','used whenever the patient is on a ventilator','not carried on the trucks'], 1),
('operations', 'ops-known-before', 'Our operation', 'Before you touch the truck, you will usually know:', array['nothing beyond an address','their name, diagnosis, medications, medical devices and destination','the patient name only','whichever details the family has given dispatch'], 1),
('operations', 'ops-the-risk', 'Our operation', 'The briefing describes the main risk of this job as:', array['not knowing what you will find when you arrive','being responsible for a medically complex patient for 45 minutes or longer, with more help not immediately available','the number of miles driven each shift','exposure to violence at the roadside'], 1),
('operations', 'ops-patient-types', 'Our operation', 'Which describes the patients this operation routinely moves?', array['mostly walking patients going to appointments','patients on ventilators, sedation and infusions, alongside stable patients going home','trauma patients straight from the roadside','newborns only'], 1),
('operations', 'ops-mcs-patients', 'Our operation', 'Patients receiving mechanical circulatory support — an intra-aortic balloon pump, Impella or ECMO — are:', array['never moved by ground ambulance','among the patients this operation may transport','the most common patient we transport','transported only by a different company'], 1),
('operations', 'ops-stable-majority', 'Our operation', 'The briefing describes the stable transports — the patient who needs no intervention — as:', array['filler between the calls that matter','a major part of the job, and something that matters to the person on the stretcher','handled by a separate wheelchair service','transported only on weekends'], 1),
('operations', 'ops-vent-expectation', 'Our operation', 'A Kansas City paramedic is expected to:', array['manage the transport ventilator, not simply watch it','leave ventilator settings to the sending respiratory therapist','transport vented patients only with a nurse on board','switch every vented patient to a bag-valve mask for the trip'], 0),
('operations', 'ops-bring-not-train', 'Our operation', 'The briefing says we can train people on our equipment and processes. What it asks them to bring is:', array['previous critical-care transport experience','reliability, sound judgment, intellectual honesty, and a willingness to ask when they do not know','a paramedic certification','a fixed number of years in EMS'], 1),
('operations', 'ops-injury-source', 'Our operation', 'According to the briefing, injuries in this job come most often from:', array['violent patients','lifting and moving patients','road collisions','needlesticks'], 1),
('operations', 'ops-report-skill', 'Our operation', 'Taking report from an ICU nurse well means:', array['writing down what you are given and leaving promptly','getting the report and asking the questions it did not answer','asking the nurse to repeat it so it can be recorded word for word','waiting for the physician to give it instead'], 1),
('operations', 'ops-chart-justifies', 'Our operation', 'An interfacility patient care report has to establish:', array['how long the transport took','why this patient needed an ambulance and this level of care','which crew members were on the truck','the route driven between the two facilities'], 1),
('operations', 'ops-qa-sampling', 'Our operation', 'Our charts are reviewed:', array['only when a complaint is made','about a fifth of them, every month, against a written rubric','once a year at appraisal','by the receiving facility rather than by us'], 1),
('operations', 'ops-paperwork-serious', 'Our operation', 'On documentation, the briefing asks that:', array['you enjoy paperwork','you take it seriously, whether or not you enjoy it, because here it is part of the clinical work','you keep it brief so the crew stays available','you leave it to whichever partner is faster at it'], 1),
('operations', 'ops-waiting', 'Our operation', 'Waiting — at a bedside for a nurse, or at the receiving end for a bed assignment — is:', array['rare, and a sign something has gone wrong','a normal part of the shift','billed to the sending facility and therefore avoided','grounds for leaving without the patient'], 1),
('operations', 'ops-long-transports', 'Our operation', 'Transport distances on this operation:', array['are all short trips across the metro','some take 20 minutes, others several hours each way','are capped at one hour by policy','are always within a single county'], 1),
('operations', 'ops-quiet-shift', 'Our operation', 'You finish a shift having moved several patients well and having used none of your emergency skills. The briefing describes that as:', array['a slow day that should be reported to a supervisor','doing the job well — and something that takes discipline and sustained attention','a sign you were assigned the wrong truck','unusual on this operation'], 1),
('operations', 'ops-only-emergencies', 'Our operation', 'On somebody for whom a shift only feels worthwhile when they use emergency procedures, the briefing says:', array['they will adjust within a few months','this role will probably not be a good fit','they should apply as a paramedic rather than an EMT','they will be given the busier trucks'], 1),
('operations', 'ops-guest', 'Our operation', 'On most calls in this operation, in someone else’s ICU or nursing facility, you are:', array['in charge of the scene, as on a 911 call','a guest in someone else’s workplace','responsible for the unit until you leave','there only to collect paperwork'], 1),
('operations', 'ops-reputation', 'Our operation', 'How a crew behaves in a facility hallway matters because:', array['the facilities score every crew formally each quarter','you will see the same staff every week, and it is most of our reputation','the hallways are monitored by hospital security','it affects the billing for the transport'], 1),
('operations', 'ops-no-supervisor', 'Our operation', 'Most of the time on this operation, no supervisor is standing beside you. The briefing says what follows from that is:', array['crews are checked on by radio instead','we have to be able to trust how you treat patients, families and facility staff when nobody from AMR is in the room','decisions can wait until a supervisor is reached','new employees are paired with a supervisor for their first year'], 1),
('operations', 'ops-hallway-sjt', 'Our operation', 'An ICU nurse keeps you waiting forty minutes and is short with you when she finally gives report. The response that fits this operation is to:', array['match her tone so it does not happen again','stay courteous and get the report the patient needs — courtesy here supports patient care and is part of the job','say nothing at the time and leave the incident out of the record','call dispatch from the hallway to have the transport reassigned'], 1),
('operations', 'ops-career-direction', 'Our operation', 'The career path the briefing describes runs toward:', array['scene response and rescue work','critical care, field training, education and quality review','dispatch and communications','hospital employment'], 1),
('operations', 'ops-advancement', 'Our operation', 'Field training officer, preceptor, instructor and quality-review roles here are earned through:', array['time in the position','clinical performance, dependable work, strong documentation, and the trust of the people working beside you','a written examination','seniority within the company'], 1),
('operations', 'ops-linn-cass', 'Our operation', 'The 911 work this company does in the region is:', array['run out of the Kansas City interfacility trucks','in Linn County, Kansas — a rural 911 operation with two round-the-clock trucks — and Cass County, Missouri, which runs a transport truck of its own','contracted out to another provider','available to Kansas City crews as overtime shifts'], 1),
('operations', 'ops-not-a-queue', 'Our operation', 'Taking a seat here in order to move across to a 911 operation later is:', array['the usual route people take, and it works','not how it works — those are separate operations with their own positions and hiring, and this job is not a waiting list for a 911 opening','possible after twelve months of service','decided by seniority each January'], 1),
('operations', 'ops-say-so', 'Our operation', 'If 911 response is the career an applicant actually wants, the briefing asks them to:', array['keep it to themselves until after the probation period','say so — it is a respectable answer, and we would rather hear it now','apply anyway and decide later','withdraw their application'], 1),
('operations', 'ops-ask-dont-guess', 'Our operation', 'On this operation, when you do not know something:', array['asking is the professional behavior and guessing is the dangerous one','you are expected to work it out yourself before asking','you should ask the facility staff rather than your own people','it is best raised after the transport, in the report'], 0),
('operations', 'ops-routine-attention', 'Our operation', 'The attention this operation expects on a routine transport is:', array['proportionate — less than on a critical one','the same level you bring to a critical one','whatever the schedule allows that day','set by the sending facility'], 1),
('operations', 'ops-honest-chart', 'Our operation', 'The standard the briefing sets for your documentation is that it is:', array['complete enough to satisfy billing','accurate and honest, including your own mistakes','brief, so the crew stays available','written to match what the sending facility recorded'], 1),
('operations', 'ops-neop-length', 'Our operation', 'The New Employee Orientation Program classroom runs:', array['two days, on your first weekend','roughly a week and a half, and is held every other month','six weeks, full time','entirely online, at your own pace'], 1),
('operations', 'ops-medic-block', 'Our operation', 'Paramedics coming into Kansas City add which block to the standard orientation?', array['rescue and extrication','ventilator management, and vasopressor and sedative infusions','dispatch and radio operations','community paramedicine'], 1),
('operations', 'ops-release', 'Our operation', 'You are released to work as a crew member:', array['on a fixed date at the end of orientation','after roughly 20 to 30 patient contacts, and only once you have shown you can do the work safely and consistently','once you have completed ninety days','as soon as the classroom week finishes'], 1),
('fit', 'fit-own-time', 'What you want', 'Which of these have you done in the last two years, on your own time or at your own expense?', array['A course on the sicker end of patient care — critical care, ventilators, cardiac','A fire academy course, or a department’s entrance or physical ability test','A CPR, instructor or teaching certification','None of these — the training I have done has come through work'], null),
('fit', 'fit-paid-class', 'What you want', 'We will pay for one course of your choosing and give you the days off for it. You pick:', array['Vehicle extrication and rescue','Field training officer and preceptor school','Ventilators, pumps and critical care transport','Advanced cardiac life support'], null),
('fit', 'fit-compliment', 'What you want', 'At the end of a shift, which would you rather have said about you?', array['They kept their head when it all went bad.','The new people ask for them.','That patient got there in the same shape they left in.','Nothing in particular — I would rather the work spoke for itself.'], null),
('fit', 'fit-story', 'What you want', 'A friend asks what your last job was really like. The first thing you find yourself telling them about is:', array['The people you worked with','The worst call you ran','A patient you got right when it would have been easy to get wrong','What it paid, and how the schedule worked'], null),
('fit', 'fit-wear-down', 'What you want', 'Which of these would wear you down faster?', array['A shift where nothing happened','A shift where you never got a minute to yourself','Being blamed for something that was not your fault','Working alongside somebody you did not respect'], null),
('fit', 'fit-five-years', 'What you want', 'Five years from now, which of these would you be happiest to have become?', array['The one who teaches the new people','The one on a busy truck, first out the door','The one in an office role, with regular hours and a say in how things run','The one they send with the sickest patients'], null),
('fit', 'fit-pitch', 'What you want', 'Somebody asks you to help talk a friend into applying where you work. The line you would use is:', array['You will see things most people never see.','You will get properly good at looking after sick people.','It is steady, and they treat you like an adult.','It is a good place to start.'], null),
('fit', 'fit-applications', 'What you want', 'How many other places have you applied to in the last three months?', array['This is the only one','Two or three, all much the same kind of work','Several, including fire departments or 911 services','A lot — I am looking broadly at the moment'], null),
('fit', 'fit-swap', 'What you want', 'A partner offers to swap shifts with you. You would most want the one that:', array['Puts you with the partner you would learn the most from','Runs the busiest trucks','Gets you home on time','Takes the most complicated patients'], null),
('fit', 'fit-leave', 'What you want', 'Suppose you take this job. What would be most likely to start you looking somewhere else?', array['A schedule that stopped working for your life','Pay that stopped keeping up','An opening somewhere you had been waiting on','Feeling like you had stopped learning anything'], null),
('fit', 'fit-least', 'What you want', 'Which part of this job do you expect to like least?', array['The waiting — at bedsides, and for beds','The documentation','How seldom the emergency skills get used','The long transports'], null),
('fit', 'fit-charts', 'What you want', 'On paperwork, which is closest to you?', array['I would rather be the one whose charts nobody has to come back and ask about','I get it done and I keep it short','It is the part I have to be disciplined about','I have not written many yet'], null),
('fit', 'fit-experience', 'What you want', 'Which best describes the EMS work you have done so far?', array['None yet — I am new to it','911 or scene work','Transport or interfacility work','Both scene and transport work'], null)
) as v(section, code, domain, stem, options, answer)
on conflict (code) where code is not null do update
  set section = excluded.section,
      domain  = excluded.domain,
      stem    = excluded.stem,
      options = excluded.options,
      answer  = excluded.answer,
      active  = true;

-- Retire anything no longer in the bank. Never deleted — see the header.
update public.exam_questions
   set active = false
 where program = 'neop'
   and active
   and code not in ('clin-scene-safety', 'clin-bsi', 'clin-avpu', 'clin-adult-hr', 'clin-unstable-reassess', 'clin-trend', 'clin-early-shock', 'clin-bleeding-first', 'clin-tourniquet', 'clin-airway-first', 'clin-opa-gag', 'clin-npa-size', 'clin-vent-rate', 'clin-chest-rise', 'clin-nrb-flow', 'clin-hypoxia', 'clin-copd-oxygen', 'clin-pulseox-co', 'clin-position-resp', 'clin-suction', 'clin-recovery-position', 'clin-peds-airway', 'clin-cpr-rate', 'clin-cpr-depth', 'clin-aed', 'clin-cpr-quality', 'clin-glucose-check', 'clin-oral-glucose', 'clin-anaphylaxis', 'clin-stroke-lkw', 'clin-seizure-status', 'clin-aspirin-why', 'clin-nitro-check', 'clin-spine', 'clin-refusal', 'clin-heavy-lift', 'clin-straps', 'clin-confused-safety', 'clin-handover', 'clin-chart-timing', 'clin-chart-honest', 'clin-equipment-check', 'ops-primary-work', 'ops-transport-kinds', 'ops-normal-call', 'ops-geography', 'ops-volume', 'ops-already-a-patient', 'ops-our-responsibility', 'ops-what-could-change', 'ops-scene-calls', 'ops-standby-aid', 'ops-lights-sirens', 'ops-known-before', 'ops-the-risk', 'ops-patient-types', 'ops-mcs-patients', 'ops-stable-majority', 'ops-vent-expectation', 'ops-bring-not-train', 'ops-injury-source', 'ops-report-skill', 'ops-chart-justifies', 'ops-qa-sampling', 'ops-paperwork-serious', 'ops-waiting', 'ops-long-transports', 'ops-quiet-shift', 'ops-only-emergencies', 'ops-guest', 'ops-reputation', 'ops-no-supervisor', 'ops-hallway-sjt', 'ops-career-direction', 'ops-advancement', 'ops-linn-cass', 'ops-not-a-queue', 'ops-say-so', 'ops-ask-dont-guess', 'ops-routine-attention', 'ops-honest-chart', 'ops-neop-length', 'ops-medic-block', 'ops-release', 'fit-own-time', 'fit-paid-class', 'fit-compliment', 'fit-story', 'fit-wear-down', 'fit-five-years', 'fit-pitch', 'fit-applications', 'fit-swap', 'fit-leave', 'fit-least', 'fit-charts', 'fit-experience');

-- Confirm the draw can be filled: 12 clinical, 16 operations, and at least one
-- preference item are needed before a candidate can start.
select section, count(*) filter (where active) as active_items, count(*) as total_items
  from public.exam_questions
 where program = 'neop'
 group by section
 order by section;


-- The app calls these functions through PostgREST, which answers from a cached
-- copy of the schema. Supabase usually reloads it on its own; this makes sure,
-- because the failure mode is an exam that reports itself as unavailable while
-- the database is in fact perfectly ready.
notify pgrst, 'reload schema';
