-- ---------------------------------------------------------------------------
-- Remove the AEMT selection exam's closing date entirely. The exam is open.
--
-- WHY THE 6 SEPTEMBER REOPEN DID NOT TAKE. Three files in this repo define
-- exam_start, and only one of them moved:
--
--   1. migrations/2026-09-04-1-reopen-aemt-selection-exam.sql   6 Sep  (moved)
--   2. neop_install.sql                                      17 Aug  (stale)
--   3. schema.sql                                            17 Aug  (stale)
--
-- neop_install.sql is the file this repo tells you to paste when the exam looks
-- broken — its own header opens with "IF THE APP STILL SAYS THE EXAM IS
-- UNAVAILABLE after this runs". It is generated by scripts/gen-neop-exam.mjs
-- from a list of migrations that had not been told about the reopen, so it
-- carried the 17 August cutoff. Running it does exactly what it says on the
-- tin and re-creates exam_start whole — putting the expired cutoff back and
-- silently undoing the reopen. Doing the obvious thing when the exam appeared
-- shut was what kept it shut.
--
-- All three now agree, and check:neop fails if any file under supabase/ ever
-- carries an AEMT cutoff again.
--
-- WHY NO DATE RATHER THAN A LATER ONE. A cutoff is a constant compiled into a
-- function body. Moving it means a migration, a paste into the SQL Editor and a
-- client deploy that all have to land together, and the failure mode when they
-- do not is silent: the exam is shut and nobody is told. That is the second
-- time in three weeks. Closing the window is an administrative decision, and it
-- is made better by a person looking at who has sat it than by a timestamp
-- nobody can see. Close it by retiring the bank or taking the link down.
--
-- This makes AEMT match NEOP, which has been rolling from the start for the
-- same reason.
--
-- THE CLIENT COPY MOVES WITH IT. src/lib/exam.ts sets deadlineIso to null in
-- the same commit, so the page stops pre-empting the server with its own
-- "closed" screen and stops printing a deadline that no longer exists.
--
-- exam_submit is deliberately NOT touched. It bounds an attempt on its own
-- window — started_at + limit_seconds + grace — which is the only clock a
-- candidate should ever be cut off by.
-- ---------------------------------------------------------------------------

create or replace function public.exam_start(
  p_name text,
  p_email text,
  p_attested boolean default null,
  p_signature text default null,
  p_attestation_hash text default null,
  p_program text default 'aemt'
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_email   text := lower(trim(p_email));
  v_name    text := trim(p_name);
  v_sign    text := nullif(trim(coalesce(p_signature, '')), '');
  v_program text := coalesce(nullif(trim(p_program), ''), 'aemt');
  -- Per-program configuration: the clock and the draw. NEITHER PROGRAM HAS A
  -- CLOSING DATE, and there is no v_cutoff here to set one — an exam that
  -- closes on a constant compiled into this function is an exam that silently
  -- stops working for everyone after that date, and needs a migration, a paste
  -- and a client deploy to reopen. That failure has now happened twice. Closing
  -- the window is done by retiring the bank or taking the link down, where
  -- somebody can see it has happened.
  v_limit   int;
  v_draw    int;
  v_clin    int;
  v_ops     int;
  v_have    int;
  v_attempt public.exam_attempts;
  v_qids    bigint[];
  v_total   int;
  v_questions jsonb;
begin
  if v_program not in ('aemt', 'neop') then
    return jsonb_build_object('error', 'Unknown exam.');
  end if;
  if v_name = '' or v_email = '' then
    return jsonb_build_object('error', 'Name and email are required.');
  end if;

  if v_program = 'aemt' then
    v_limit  := 25 * 60;
    v_draw   := 50;
  else
    v_limit  := 35 * 60;
    v_clin   := 12;
    v_ops    := 16;                         -- every preference item is served
  end if;

  select * into v_attempt from public.exam_attempts a
    where a.email = v_email
      and a.program = v_program
      and a.voided_at is null          -- a reset attempt no longer counts
    order by a.started_at desc limit 1;

  if found then
    if v_attempt.submitted_at is not null then
      return jsonb_build_object('error', 'already_taken');
    end if;
    if now() > v_attempt.started_at + make_interval(secs => v_attempt.limit_seconds) then
      return jsonb_build_object('error', 'expired');
    end if;
    v_qids := v_attempt.question_ids;
  else
    if v_program = 'aemt' then
      select array_agg(id) into v_qids
        from (select id from public.exam_questions
               where active and program = 'aemt'
               order by random() limit v_draw) s;
      if v_qids is null or array_length(v_qids, 1) < v_draw then
        return jsonb_build_object('error', 'bank_too_small');
      end if;
    else
      -- Stratified: a fixed number from each scored section, then EVERY
      -- preference item. The preference items are not sampled — an interviewer
      -- comparing two candidates needs them to have answered the same
      -- questions, and a random subset takes that away.
      --
      -- sect_ord 1/2/3 is patient care, then preferences, then our operation.
      -- See the header: the operations section is the one that tells a
      -- candidate what we want to hear, so it comes after we have asked.
      select count(*) into v_have from public.exam_questions
        where active and program = 'neop' and section = 'clinical';
      if v_have < v_clin then return jsonb_build_object('error', 'bank_too_small'); end if;
      select count(*) into v_have from public.exam_questions
        where active and program = 'neop' and section = 'operations';
      if v_have < v_ops then return jsonb_build_object('error', 'bank_too_small'); end if;
      select count(*) into v_have from public.exam_questions
        where active and program = 'neop' and section = 'fit';
      if v_have < 1 then return jsonb_build_object('error', 'bank_too_small'); end if;

      with picked as (
        select id, 1 as sect_ord from (
          select id from public.exam_questions
           where active and program = 'neop' and section = 'clinical'
           order by random() limit v_clin) c
        union all
        select id, 2 from public.exam_questions
         where active and program = 'neop' and section = 'fit'
        union all
        select id, 3 from (
          select id from public.exam_questions
           where active and program = 'neop' and section = 'operations'
           order by random() limit v_ops) o
      )
      select array_agg(id order by sect_ord, random()) into v_qids from picked;
    end if;

    -- Only keyed items count toward the score, so only keyed items count
    -- toward the total. Otherwise a candidate who answers every scored item
    -- correctly is recorded at 68%.
    select count(*) into v_total from public.exam_questions
      where id = any(v_qids) and scored;
    if coalesce(v_total, 0) = 0 then
      return jsonb_build_object('error', 'bank_too_small');
    end if;

    insert into public.exam_attempts (
      name, email, question_ids, total, limit_seconds, program,
      attested, signature, attested_at, attestation_hash)
      values (
        v_name, v_email, v_qids, v_total, v_limit, v_program,
        p_attested, v_sign,
        case when p_attested is true then now() else null end,
        nullif(trim(coalesce(p_attestation_hash, '')), ''))
      returning * into v_attempt;
  end if;

  select jsonb_agg(
           jsonb_build_object(
             'id', q.id, 'domain', q.domain, 'stem', q.stem, 'options', q.options,
             'section', q.section, 'scored', q.scored)
           order by array_position(v_qids, q.id))
    into v_questions
    from public.exam_questions q
    where q.id = any(v_qids);

  return jsonb_build_object(
    'attemptId', v_attempt.id,
    'startedAt', v_attempt.started_at,
    'limitSeconds', v_attempt.limit_seconds,
    'program', v_attempt.program,
    'questions', coalesce(v_questions, '[]'::jsonb));
end;
$$;
